environments:
  default:
    values: 
      - environmentName: default
  fungible:
    values:
     - environmentName: {{ env "ENVIRONMENT" }}
       kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
     - config/fungible.yaml
  dev:
    values:
      - environmentName: dev
        kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
      - config/dev.yaml
  frontend:
    values:
      - environmentName: frontend
        kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
      - config/frontend.yaml
  staging:
    values:
      - environmentName: staging
        kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
      - config/staging.yaml
  holesky:
    values:
    - environmentName: holesky
      kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
    - config/holesky.yaml
  holesky-v3:
    values:
    - environmentName: holesky-v3
      kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
    - config/holesky-v3.yaml
  prod:
    values:
      - environmentName: prod
        kubeContext: gke_direct-pixel-353917_europe-west1_gasp-prod
      - config/prod.yaml