environments:
  fungible:
    kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
    values:
     - environmentName: '{{ env "ENVIRONMENT" }}'
     - config/fungible.yaml
  dev:
    kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
    values:
      - environmentName: dev
      - config/dev.yaml
  frontend:
    kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
    values:
      - environmentName: frontend
      - config/frontend.yaml
  holesky:
    kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
    values:
    - environmentName: holesky
    - config/holesky.yaml
  holesky-v3:
    kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
    values:
    - environmentName: holesky-v3
    - config/holesky-v3.yaml
  prod:
    kubeContext: gke_direct-pixel-353917_europe-west1_gasp-prod
    values:
      - environmentName: prod
      - config/prod.yaml