environments: 
  default:
    values:
     - config/default.yaml
---
helmDefaults:
  wait: true

releases:
  - name: anvil
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: ../helm-charts/anvil-testnet
    values:
      - environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}

  - name: eigen-aggregator
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/aggregator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        args: {{ toYaml .Values.aggregatorArgs | nindent 8 }}
        configFiles: {{ toYaml .Values.aggregatorConfigFiles | nindent 8 }}
  - name: eigen-operator
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/operator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        args: {{ toYaml .Values.operatorArgs | nindent 8 }}
        configFiles: {{ toYaml .Values.operatorConfigFiles | nindent 8 }}
        rpcPort: 9010
        prometheus:
          enabled: true