bases: ['environments.yaml']
---
helmDefaults:
  kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
  wait: false
  diffArgs:
    - "--suppress" 
    - "Job"
  # TODO: To remove after updating Helm charts
    - "--suppress-output-line-regex"
    - "(application|component|heritage|service|isP2P|isRpc):.+"
  
helmfiles:
  - path: sub-helmfiles/blockscout/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
  - path: sub-helmfiles/evm-nodes/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
  - path: sub-helmfiles/rollup-nodes/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}

releases:
  - name: avs-aggregator
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.aggregatorEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: mangatasolutions/avs-aggregator
          tag: {{ .Values | get "aggregatorImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        environment: {{ .Values.environmentName }}
        remoteCluster: {{ .Values.remoteCluster }}
        envSecrets: {{ .Values.aggregatorEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.aggregatorEnv | toYaml | nindent 10 }}

  - name: avs-finalizer
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.finalizerEnabled }}
    chart: ../helm-charts/avs-finalizer
    values:
      - image:
          repository: mangatasolutions/avs-finalizer
          tag: {{ .Values | get "finalizerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        environment: {{ .Values.environmentName }}
        envSecrets: {{ .Values.finalizerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.finalizerEnv | toYaml | nindent 10 }}

  - name: gasp-syncer
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.gaspSyncerEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: mangatasolutions/gasp-syncer
          tag: {{ .Values | get "gaspSyncerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.gaspSyncerEnv | toYaml | nindent 10 }}
        envSecrets: {{ .Values.gaspSyncerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
  
  - name: rollup-sequencer-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.sequencerEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: mangatasolutions/rollup-sequencer
          tag: {{ .Values | get "sequencerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.sequencerEnvEth | toYaml | nindent 10 }}
        envSecrets: {{ .Values.sequencerEnvSecretsEth | expandSecretRefs | toYaml | nindent 10 }}

  - name: rollup-sequencer-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ and .Values.sequencerEnabled .Values.enableArbitrumServices }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: mangatasolutions/rollup-sequencer
          tag: {{ .Values | get "sequencerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.sequencerEnvArb | toYaml | nindent 10 }}
        envSecrets: {{ .Values.sequencerEnvSecretsArb | expandSecretRefs | toYaml | nindent 10 }}

  - name: rpc-shared-dns-record
    installed: {{ eq .Values.environmentName "holesky" }}
    namespace: 'rollup-{{ .Values.environmentName }}'
    chart: ../helm-charts/shared-dns-record
    values:
      - url: 'rollup-{{ .Values.environmentName }}-rpc.gasp.xyz'
        serviceSelector:
          role: rpc

  - name: rpc-shared-dns-record-testnet
    installed: {{ eq .Values.environmentName "holesky" }}
    namespace: 'rollup-{{ .Values.environmentName }}'
    chart: ../helm-charts/shared-dns-record
    values:
      - url: 'rollup-testnet-rpc.gasp.xyz'
        serviceSelector:
          role: rpc

  - name: rpc-shared-dns-record-legacy
    installed: {{ eq .Values.environmentName "holesky" }}
    namespace: 'rollup-{{ .Values.environmentName }}'
    chart: ../helm-charts/shared-dns-record
    values:
      - url: 'rollup-testnet-rpc.mangata.online'
        serviceSelector:
          role: rpc