environments: 
  default:
    values:
     - config/default.yaml
  fungible:
    values:
     - config/default.yaml
     - config/fungible.yaml
  dev:
    values:
    - config/default.yaml
    - config/dev.yaml
  frontend:
    values:
    - config/default.yaml
    - config/frontend.yaml
  testnet:
    values:
     - config/testnet.yaml
---
helmDefaults:
  kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
  wait: false

releases:
  - name: anvil
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.anvilEnabled }}
    chart: ../helm-charts/anvil-testnet
    values:
      - image:
          repository: mangatasolutions/anvil
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        enablePersistence: {{ .Values.anvilEnablePersistence }}

  - name: avs-aggregator
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.aggregatorEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: mangatasolutions/avs-aggregator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        envSecrets: {{ .Values.aggregatorEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}

  - name: avs-finalizer
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.finalizerEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: mangatasolutions/avs-finalizer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        rpcPort: 9010
        enableServiceMonitorCollectors: {{ .Values.finalizerEnableServiceMonitorCollectors }}
        prometheus:
          enabled: true
        envSecrets: {{ .Values.finalizerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}
  - name: avs-finalizer-2
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.secondFinalizerEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: mangatasolutions/avs-finalizer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        rpcPort: 9010
        enableServiceMonitorCollectors: {{ .Values.finalizerEnableServiceMonitorCollectors }}
        prometheus:
          enabled: true
        envSecrets: {{ .Values.finalizerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}

  - name: rollup-updater
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.updaterEnabled }}
    chart: ../helm-charts/rollup-updater
    values:
      - image:
          repository: mangatasolutions/rollup-updater
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        walletPrivateKey: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-private-key
        ethChainUrl: {{ .Values.updaterEthChainUrl | fetchSecretValue | quote }}
        env: {{ .Values.updaterEnv | toYaml | nindent 10 }}
  
  - name: rollup-sequencer
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.sequencerEnabled }}
    chart: ../helm-charts/rollup-sequencer
    values:
      - image:
          repository: mangatasolutions/rollup-sequencer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        mnemonic: {{ .Values.firstSequencerMnemonic | fetchSecretValue | quote }}
        ethChainUrl:  {{ .Values.sequencerEthChainUrl | fetchSecretValue | quote }}
        env: {{ .Values.sequencerEnv | toYaml | nindent 10 }}
  - name: rollup-sequencer-2
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.secondSequencerEnabled }}
    chart: ../helm-charts/rollup-sequencer
    values:
      - image:
          repository: mangatasolutions/rollup-sequencer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        mnemonic: {{ .Values.secondSequencerMnemonic | fetchSecretValue | quote }}
        ethChainUrl:  {{ .Values.sequencerEthChainUrl | fetchSecretValue | quote }}
        env: {{ .Values.sequencerEnv | toYaml | nindent 10 }}
