environments: 
  default:
    values:
     - config/default.yaml
  fungible:
    values:
     - config/default.yaml
     - config/fungible.yaml
  dev:
    values:
    - config/default.yaml
    - config/dev.yaml
  goerli:
    values:
     - config/default.yaml
     - config/goerli.yaml
---
helmDefaults:
  kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
  wait: false

releases:
  - name: anvil
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.anvilEnabled }}
    chart: ../helm-charts/anvil-testnet
    values:
      - environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}

  - name: avs-aggregator
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.aggregatorEnabled }}
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/avs-aggregator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        envSecrets: {{ .Values.aggregatorEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}
  - name: avs-finalizer
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.finalizerEnabled }}
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/avs-finalizer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        rpcPort: 9010
        enableServiceMonitorCollectors: {{ .Values.finalizerEnableServiceMonitorCollectors }}
        prometheus:
          enabled: true
        envSecrets: {{ .Values.finalizerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}
  - name: rollup-updater
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.updaterEnabled }}
    chart: ../helm-charts/rollup-updater
    values:
      - image:
          repository: mangatasolutions/rollup-updater
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        walletPrivateKey: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-private-key
        ethChainUrl: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-ethereum-rpc-url
  - name: rollup-sequencer
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.sequencerEnabled }}
    chart: ../helm-charts/rollup-sequencer
    values:
      - image:
          repository: mangatasolutions/rollup-sequencer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        mnemonic: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-sequencer-mnemonic
        ethChainUrl: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-ethereum-rpc-url