environments: 
  default:
    values:
     - config/default.yaml
  fungible:
    values:
     - config/default.yaml
     - config/fungible.yaml
  goerli:
    values:
     - config/default.yaml
     - config/goerli.yaml
---
helmDefaults:
  kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
  wait: false

releases:
  - name: anvil
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.anvilEnabled }}
    chart: ../helm-charts/anvil-testnet
    values:
      - environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}

  - name: eigen-aggregator
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.aggregatorEnabled }}
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/aggregator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        args: {{ toYaml .Values.aggregatorArgs | nindent 8 }}
        configFiles: {{ toYaml .Values.aggregatorConfigFiles | nindent 8 }}
  - name: eigen-operator  
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.operatorEnabled }}
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/operator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        args: {{ toYaml .Values.operatorArgs | nindent 8 }}
        configFiles: {{ toYaml .Values.operatorConfigFiles | nindent 8 }}
        rpcPort: 9010
        enableServiceMonitorCollectors: {{ .Values.operatorEnableServiceMonitorCollectors }}
        prometheus:
          enabled: true
  - name: mangata-updater
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.updaterEnabled }}
    chart: ../helm-charts/mangata-updater
    values:
      - image:
          repository: mangatasolutions/mangata-updater
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        walletPrivateKey: 15cb3150921ee606d71b9def1b6392c9df1d4fea399cbcca2047d9cf84f44f06