environments: 
  default:
    values:
     - config/default.yaml
  fungible:
    values:
     - config/default.yaml
     - config/fungible.yaml
  dev:
    values:
    - config/default.yaml
    - config/dev.yaml
  frontend:
    values:
    - config/default.yaml
    - config/frontend.yaml
  testnet:
    values:
     - config/testnet.yaml
---
repositories:
  - name: ethereum-helm-charts
    url: https://ethpandaops.github.io/ethereum-helm-charts
    
helmDefaults:
  kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
  wait: false

releases:
  - name: evm-node-eth
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.evmNodeEnabled }}
    chart: ../helm-charts/evm-node
    values:
      - image:
          repository: mangatasolutions/anvil
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        nameOverride: 'evm-node-eth'
        envSelector: ethereum-stub
        enablePersistence: true
  
  - name: evm-node-arb
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.anvilEnabled }}
    chart: ../helm-charts/evm-node
    values:
      - image:
          repository: mangatasolutions/anvil
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        nameOverride: 'evm-node-arb'
        envSelector: arbitrum-stub
        enablePersistence: true

  - name: avs-aggregator
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.aggregatorEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: mangatasolutions/avs-aggregator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        envSecrets: {{ .Values.aggregatorEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}

  - name: avs-finalizer
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.finalizerEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: mangatasolutions/avs-finalizer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        rpcPort: 9010
        enableServiceMonitorCollectors: {{ .Values.finalizerEnableServiceMonitorCollectors }}
        prometheus:
          enabled: true
        envSecrets: {{ .Values.finalizerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}
  - name: avs-finalizer-2
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.secondFinalizerEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: mangatasolutions/avs-finalizer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        rpcPort: 9010
        enableServiceMonitorCollectors: {{ .Values.finalizerEnableServiceMonitorCollectors }}
        prometheus:
          enabled: true
        envSecrets: {{ .Values.finalizerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}

  - name: rollup-updater
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.updaterEnabled }}
    chart: ../helm-charts/rollup-updater
    values:
      - image:
          repository: mangatasolutions/rollup-updater
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        walletPrivateKey: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-private-key
        ethChainUrl: {{ .Values.updaterEthChainUrl | fetchSecretValue | quote }}
        env: {{ .Values.updaterEnv | toYaml | nindent 10 }}
  
  - name: rollup-sequencer
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.sequencerEnabled }}
    chart: ../helm-charts/rollup-sequencer
    values:
      - image:
          repository: mangatasolutions/rollup-sequencer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        mnemonic: {{ .Values.firstSequencerMnemonic | fetchSecretValue | quote }}
        ethChainUrl:  {{ .Values.sequencerEthChainUrl | fetchSecretValue | quote }}
        env: {{ .Values.sequencerEnv | toYaml | nindent 10 }}
  - name: rollup-sequencer-2
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.secondSequencerEnabled }}
    chart: ../helm-charts/rollup-sequencer
    values:
      - image:
          repository: mangatasolutions/rollup-sequencer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        mnemonic: {{ .Values.secondSequencerMnemonic | fetchSecretValue | quote }}
        ethChainUrl:  {{ .Values.sequencerEthChainUrl | fetchSecretValue | quote }}
        env: {{ .Values.sequencerEnv | toYaml | nindent 10 }}

  - name: blockscout
    namespace: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.blockscoutEnabled }}
    chart: ethereum-helm-charts/blockscout
    values:
      - config:
          MIX_ENV: 'rollup-{{ requiredEnv "ENVIRONMENT" }}'
          ETHEREUM_JSONRPC_VARIANT: 'geth'
          ETHEREUM_JSONRPC_HTTP_URL: http://evm-node:8545
          ETHEREUM_JSONRPC_WS_URL: ws://evm-node:8545
          ETHEREUM_JSONRPC_TRACE_URL: http://evm-node:8545
        image:
          tag: 6.6.0
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            external-dns.alpha.kubernetes.io/hostname: blockscout.rollup-{{ requiredEnv "ENVIRONMENT" }}.gasp.xyz
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: 'true'
          hosts:
            - host: blockscout.rollup-{{ requiredEnv "ENVIRONMENT" }}.gasp.xyz
              paths:
                - pathType: Prefix
                  path: '/'
          tls:
            - hosts: ['blockscout.rollup-{{ requiredEnv "ENVIRONMENT" }}.gasp.xyz']
              secretName: blockscout-tls
          smart-contract-verifier-http:
            enabled: true
