bases: ['environments.yaml']
---
helmDefaults:
  kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
  wait: false
  diffArgs:
    - "--suppress" 
    - "Job"
  # # TODO: To remove after updating Helm charts
  #   - "--suppress-output-line-regex"
  #   - "(application|component|heritage|service|isP2P|isRpc):.+"
  
helmfiles:
  - path: sub-helmfiles/blockscout/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
  - path: sub-helmfiles/rollup-nodes/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}

releases:
  - name: avs-aggregator
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.aggregatorEnabled }}
    chart: ../helm-charts/rollup-node
    values:
      - image:
          repository: gaspxyz/avs-aggregator
          tag: {{ .Values | get "aggregatorImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        environment: {{ .Values.environmentName }}
        remoteCluster: {{ .Values.remoteCluster }}
        envSecrets: {{ .Values.aggregatorEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.aggregatorEnv | toYaml | nindent 10 }}

  - name: avs-finalizer
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.finalizerEnabled }}
    chart: ../helm-charts/avs-finalizer
    values:
      - image:
          repository: gaspxyz/avs-finalizer
          tag: {{ .Values | get "finalizerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        environment: {{ .Values.environmentName }}
        envSecrets: {{ .Values.finalizerEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
        env: {{ .Values.finalizerEnv | toYaml | nindent 10 }}

  - name: updater
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.updaterEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/updater
          tag: {{ .Values | get "updaterImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.updaterEnv | toYaml | nindent 10 }}
        envSecrets: {{ .Values.updaterEnvSecrets | expandSecretRefs | toYaml | nindent 10 }}
  
  - name: sequencer-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.sequencerEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/sequencer
          tag: {{ .Values | get "sequencerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.sequencerEnvEth | toYaml | nindent 10 }}
        envSecrets: {{ .Values.sequencerEnvSecretsEth | expandSecretRefs | toYaml | nindent 10 }}

  - name: sequencer-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ and .Values.sequencerEnabled .Values.enableArbitrumServices }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/sequencer
          tag: {{ .Values | get "sequencerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.sequencerEnvArb | toYaml | nindent 10 }}
        envSecrets: {{ .Values.sequencerEnvSecretsArb | expandSecretRefs | toYaml | nindent 10 }}
  
  - name: ferry-deposit-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.ferryDepositEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/ferry-deposit
          tag: {{ .Values | get "ferryDepositImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.ferryDepositEnvEth | toYaml | nindent 10 }}
        envSecrets: {{ .Values.ferryDepositEnvSecretsEth | expandSecretRefs | toYaml | nindent 10 }}
  - name: ferry-deposit-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.ferryDepositEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/ferry-deposit
          tag: {{ .Values | get "ferryDepositImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.ferryDepositEnvArb | toYaml | nindent 10 }}
        envSecrets: {{ .Values.ferryDepositEnvSecretsArb | expandSecretRefs | toYaml | nindent 10 }}

  - name: ferry-withdrawal-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.ferryWithdrawalEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/ferry-withdrawal
          tag: {{ .Values | get "ferryWithdrawalImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.ferryWithdrawalEnvEth | toYaml | nindent 10 }}
        envSecrets: {{ .Values.ferryWithdrawalEnvSecretsEth | expandSecretRefs | toYaml | nindent 10 }}
  - name: ferry-withdrawal-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.ferryWithdrawalEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/ferry-withdrawal
          tag: {{ .Values | get "ferryWithdrawalImageTag" (requiredEnv "IMAGE_TAG") | quote }}
        env: {{ .Values.ferryWithdrawalEnvArb | toYaml | nindent 10 }}
        envSecrets: {{ .Values.ferryWithdrawalEnvSecretsArb | expandSecretRefs | toYaml | nindent 10 }}

  - name: closer-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.closerEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/ferry-withdrawal
          tag: {{ .Values | get "closerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
          # `args` param is used to override the default command in the Dockerfile
          args: ["node", "build/src/closer.js"]
        env: {{ .Values.closerEnvEth | toYaml | nindent 10 }}
        envSecrets: {{ .Values.closerEnvSecretsEth | expandSecretRefs | toYaml | nindent 10 }}
  - name: closer-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.closerEnabled }}
    chart: ../helm-charts/common-deployment
    values:
      - image:
          repository: gaspxyz/ferry-withdrawal
          tag: {{ .Values | get "closerImageTag" (requiredEnv "IMAGE_TAG") | quote }}
          # `args` param is used to override the default command in the Dockerfile
          args: ["node", "build/src/closer.js"]
        env: {{ .Values.closerEnvArb | toYaml | nindent 10 }}
        envSecrets: {{ .Values.closerEnvSecretsArb | expandSecretRefs | toYaml | nindent 10 }}

  - name: evm-node-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.evmNode.enabled }}
    chart: ../helm-charts/evm-node
    values:
      - image:
          repository: gaspxyz/gasp-contracts
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        environment: {{ .Values.environmentName }}
        nameOverride: 'evm-node-eth'
        envSelector: ethereum-stub
        enablePersistence: true
        verifierEnabled: {{ .Values | get "blockscoutEnabled" false }}
        verifierUrl: 'http://blockscout-eth-blockscout-stack-blockscout-svc:80/api'
        # If customChainspecUrlEth is not set, the node will use the default chainspec instead
        customGenesisUrl: {{ .Values | get "evmNode.customGenesisUrlEth" "" }}
  
  - name: evm-node-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ and .Values.evmNode.enabled .Values.enableArbitrumServices | toYaml }}
    chart: ../helm-charts/evm-node
    values:
      - image:
          repository: gaspxyz/gasp-contracts
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        environment: {{ .Values.environmentName }}
        nameOverride: 'evm-node-arb'
        envSelector: arbitrum-stub
        enablePersistence: true
        verifierEnabled: {{ .Values | get "blockscoutEnabled" false }}
        verifierUrl: 'http://blockscout-arb-blockscout-stack-blockscout-svc:80/api'
        # If customChainspecUrlArb is not set, the node will use the default chainspec instead
        customGenesisUrl: {{ .Values | get "evmNode.customGenesisUrlArb" "" }}