nodeLinker: node-modules
enableTransparentWorkspaces: true
nmMode: hardlinks-local

# This helps Yarn be more tolerant of peer dependency mismatches
pnpFallbackMode: all

# These settings make Yarn more lenient with peer dependencies
packageExtensions:
  '@walletconnect/modal-core@*':
    peerDependencies:
      'react': '*'
  '@walletconnect/modal@*':
    peerDependencies:
      'react': '*'
  '@walletconnect/modal-ui@*':
    peerDependencies:
      'react': '*'
  '@walletconnect/ethereum-provider@*':
    peerDependencies:
      'react': '*'
  '@wagmi/connectors@*':
    peerDependencies:
      'react': '*'
  'gasp-sdk@*':
    peerDependencies:
      '@polkadot/types': '*'
      '@tanstack/react-query': '*'
      'react': '*'
  'wagmi@*':
    peerDependenciesMeta:
      '@tanstack/react-query':
        optional: true
      'react':
        optional: true
