services:
  closer-eth:
    build: .
    image: gaspxyz/ferry-withdrawal:${FERRY_WITHDRAWAL_VERSION:-localcloser}
    restart: unless-stopped
    command: ["node", "build/src/closer.js"]
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
      node-bob:
        condition: service_started
      stash-mock:
        condition: service_started
    environment:
      MANGATA_NODE_URL: ${ETH_CLOSER_MANGATA_NODE_URL}
      ETH_CHAIN_URL: ${ETH_CLOSER_ETH_CHAIN_URL}
      STASH_URL: http://stash-mock:8080
      MANGATA_CONTRACT_ADDRESS: ${ETH_CLOSER_MANGATA_CONTRACT_ADDRESS}
      PRIVATE_KEY: ${ETH_CLOSER_PRIVATE_KEY}
      TOKENS_TO_TRACK: ${ETH_CLOSER_TOKENS_TO_TRACK}
      L1_CHAIN: ${ETH_CLOSER_L1_CHAIN}
      TX_COST: ${ETH_CLOSER_TX_COST}
      LOG: ${ETH_CLOSER_LOG}
      DELAY: ${ETH_CLOSER_DELAY}

  stash-mock:
    image: wiremock/wiremock
    ports:
      - 80:8080
    volumes:
      - ./stash-mock:/home/wiremock/mappings/
