services:
  eth-ferry-deposit:
    restart: unless-stopped
    platform: linux/amd64
    image: mangatasolutions/ferry-deposit:local-eth
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    build: .
    environment:
      MANGATA_NODE_URL: ${ETH_FERRY_DEPOSIT_MANGATA_NODE_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ETH_FERRY_DEPOSIT_CHAIN_URL:-wss://ethereum.publicnode.com}
      MANGATA_CONTRACT_ADDRESS: ${ETH_FERRY_MANGATA_CONTRACT_ADDRESS:-0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc}
      MNEMONIC: ${ETH_FERRY_DEPOSIT_MNEMONIC}
      L1_CHAIN: ${ETH_FERRY_DEPOSIT_L1_CHAIN}
      MIN_PROFIT: ${ETH_FERRY_DEPOSIT_MIN_PROFIT}
      TX_COST: ${ETH_FERRY_DEPOSIT_TX_COST}
      BLOCK_DELAY: ${ETH_FERRY_DEPOSIT_BLOCK_DELAY}
