[workspace.package]
authors = ["Mangata Team"]
edition = "2021"
repository = "https://github.com/gasp-xyz/mangata-node.git"

[workspace]
resolver = "2"
members = [
	'sequencer',
	'bindings',
]

[profile.dev]
split-debuginfo = "unpacked"
incremental = true
lto = true

[profile.release]
panic = 'unwind'

[profile.production]
inherits = "release"
lto = true
codegen-units = 1


[workspace.dependencies]
bindings = { path = "./bindings" }
