services:
  sequencer-eth:
    image: mangatasolutions/sequencer:${ROLLUP_SEQUENCER_VERSION:-local}
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    platform: linux/amd64
    environment:
      WATCHDOG: ${ETH_SEQUENCER_WATCHDOG}
      ETH_CHAIN_URL: ${ETH_SEQUENCER_ETH_CHAIN_URL}
      ETH_PRIV_KEY: ${ETH_SEQUENCER_ETH_PRIV_KEY}
      L1_CHAIN: ${ETH_SEQUENCER_L1_CHAIN}
      LIMIT: ${ETH_SEQUENCER_LIMIT}
      MANGATA_CONTRACT_ADDRESS: ${ETH_SEQUENCER_MANGATA_CONTRACT_ADDRESS}
      MANGATA_NODE_URL: ${ETH_SEQUENCER_MANGATA_NODE_URL}
      MNEMONIC: ${ETH_SEQUENCER_MNEMONIC}

  sequencer-arb:
    image: mangatasolutions/sequencer:${ROLLUP_SEQUENCER_VERSION:-local}
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    platform: linux/amd64
    environment:
      WATCHDOG: ${ARB_SEQUENCER_WATCHDOG}
      ETH_CHAIN_URL: ${ARB_SEQUENCER_ETH_CHAIN_URL}
      ETH_PRIV_KEY: ${ARB_SEQUENCER_ETH_PRIV_KEY}
      L1_CHAIN: ${ARB_SEQUENCER_L1_CHAIN}
      LIMIT: ${ARB_SEQUENCER_LIMIT}
      MANGATA_CONTRACT_ADDRESS: ${ARB_SEQUENCER_MANGATA_CONTRACT_ADDRESS}
      MANGATA_NODE_URL: ${ARB_SEQUENCER_MANGATA_NODE_URL}
      MNEMONIC: ${ARB_SEQUENCER_MNEMONIC}
