services:
  sequencer-eth:
    build: .
    image: gaspxyz/sequencer:${ROLLUP_SEQUENCER_VERSION:-localeth}
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    environment:
      WATCHDOG: ${ETH_SEQUENCER_WATCHDOG}
      ETH_CHAIN_URL: ${ETH_SEQUENCER_ETH_CHAIN_URL}
      PRIVATE_KEY: ${ETH_SEQUENCER_ETH_PRIV_KEY}
      L1_CHAIN: ${ETH_SEQUENCER_L1_CHAIN}
      LIMIT: ${ETH_SEQUENCER_LIMIT}
      MANGATA_CONTRACT_ADDRESS: ${ETH_SEQUENCER_MANGATA_CONTRACT_ADDRESS}
      MANGATA_NODE_URL: ${ETH_SEQUENCER_MANGATA_NODE_URL}
      MNEMONIC: ${ETH_SEQUENCER_MNEMONIC}
      TX_COST: ${ETH_SEQUENCER_TX_COST}
    ports:
      - 9898:9898

  sequencer-arb:
    build: .
    image: gaspxyz/sequencer:${ROLLUP_SEQUENCER_VERSION:-localarb}
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    environment:
      WATCHDOG: ${ARB_SEQUENCER_WATCHDOG}
      ETH_CHAIN_URL: ${ARB_SEQUENCER_ETH_CHAIN_URL}
      PRIVATE_KEY: ${ARB_SEQUENCER_ETH_PRIV_KEY}
      L1_CHAIN: ${ARB_SEQUENCER_L1_CHAIN}
      LIMIT: ${ARB_SEQUENCER_LIMIT}
      MANGATA_CONTRACT_ADDRESS: ${ARB_SEQUENCER_MANGATA_CONTRACT_ADDRESS}
      MANGATA_NODE_URL: ${ARB_SEQUENCER_MANGATA_NODE_URL}
      MNEMONIC: ${ARB_SEQUENCER_MNEMONIC}
      TX_COST: ${ARB_SEQUENCER_TX_COST}

  sequencer-base:
    build: .
    image: gaspxyz/sequencer:${ROLLUP_SEQUENCER_VERSION:-localbase}
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    environment:
      WATCHDOG: ${BASE_SEQUENCER_WATCHDOG}
      ETH_CHAIN_URL: ${BASE_SEQUENCER_ETH_CHAIN_URL}
      PRIVATE_KEY: ${BASE_SEQUENCER_ETH_PRIV_KEY}
      L1_CHAIN: ${BASE_SEQUENCER_L1_CHAIN}
      LIMIT: ${BASE_SEQUENCER_LIMIT}
      MANGATA_CONTRACT_ADDRESS: ${BASE_SEQUENCER_MANGATA_CONTRACT_ADDRESS}
      MANGATA_NODE_URL: ${BASE_SEQUENCER_MANGATA_NODE_URL}
      MNEMONIC: ${BASE_SEQUENCER_MNEMONIC}
      TX_COST: ${BASE_SEQUENCER_TX_COST}
