services:
  gasp-syncer:
    image: mangatasolutions/gasp-syncer:${GASP_SYNCER_VERSION:-local}
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      eth-stub:
        condition: service_healthy
      arbitrum-stub:
        condition: service_healthy
      eth-contracts-deployment:
        condition: service_completed_successfully
      arbitrum-contracts-deployment:
        condition: service_completed_successfully
    platform: linux/amd64
    environment:
      SOURCE_RPC_URL: ${ETH_RPC_URL:-http://eth-stub:8545}
      SOURCE_WS_URL: ${ETH_WS_URL:-ws://eth-stub:8545}
      TARGET_RPC_URL: ${ARB_RPC_URL:-http://arbitrum-stub:8546}
      TARGET_WS_URL: ${ARB_WS_URL:-ws://arbitrum-stub:8546}
      SOURCE_CHAIN_ID: ${CHAIN_ID:-31337}
      TARGET_CHAIN_ID: ${CHAIN_ID:-31337}
      AVS_REGISTRY_COORDINATOR_ADDR: 0xf5059a5D33d5853360D16C683c16e67980206f36
      GASP_SERVICE_ADDR: 0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e
      TESTNET: true
      PUSH_FIRST_INIT: true
      ECDSA_KEY_JSON: '{"address":"a0ee7a142d267c1f36714e4a8f75612f20a79720","crypto":{"cipher":"aes-128-ctr","ciphertext":"b0f6f8e3ba33f0b382b080de6661d827181de480f1a4f94bc20d66cb3d585907","cipherparams":{"iv":"4e3f9a8ca6ef8d1cd408e8aaae3c22d2"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c8f9f8cc03913e09cee7e1fd68732fac327576203ab277d740270f1dea82ee7e"},"mac":"353d65850b20d5fdb90ca2385c52e5b57662cb1d906fd58143f20a7720723cf6"},"id":"d3036cc7-d068-4f2f-9667-60aaca660e61","version":3}'
      ROOT_ECDSA_KEY_JSON: '{"address":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"26e1ebd941909ddb0ebaec8235470c8d"},"ciphertext":"adca2a84713f50c3918235e109a9b4b28ff6c8ea77b87e8aca20dc48a3a93389","kdf":"scrypt","kdfparams":{"dklen":32,"n":8192,"p":1,"r":8,"salt":"b5581b95b5c7f1449cc341db8567d4c92e4fe21bc34052dbe60bd3e2060a74a0"},"mac":"3643a9e1c0381e30ca0e250999810ecb4b213bc93bd19ad673b93870c77f55ec"},"id":"d39afde8-e06c-46d4-a7ed-1af9bb3f55a5","version":3}'
      TARGET_CHAIN_INDEX: 1
