name: Node.js Tests with Coverage
description: Runs tests for project with Coverage report

runs:
  using: composite
  steps:
    - name: 'Test'
      working-directory: stash-dev
      shell: bash
      run: yarn run test-ci
    - name: 'Report Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1
