#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod bls_pubkey_registry;
pub mod bls_pubkey_registry_storage;
pub mod bls_public_key_compendium;
pub mod bls_public_key_compendium_mock;
pub mod bls_registry_coordinator_with_indices;
pub mod bls_registry_coordinator_with_indices_harness;
pub mod delegation_manager;
pub mod delegation_manager_mock;
pub mod delegation_manager_storage;
pub mod erc20_mock;
pub mod i_delegation_manager;
pub mod i_mangata_task_manager;
pub mod i_slasher;
pub mod i_stake_registry;
pub mod i_stake_registry_stub;
pub mod i_strategy;
pub mod i_strategy_manager;
pub mod ibls_pubkey_registry;
pub mod ibls_public_key_compendium;
pub mod ibls_registry_coordinator_with_indices;
pub mod mangata_service_manager;
pub mod mangata_task_manager;
pub mod mangata_task_manager_test;
pub mod shared_types;
pub mod slasher;
pub mod slasher_mock;
pub mod stake_registry;
pub mod stake_registry_harness;
pub mod stake_registry_storage;
pub mod strategy_manager;
pub mod strategy_manager_mock;
pub mod strategy_manager_storage;
