# Default values for anvil.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: local
domainZone: mangata.online
nameOverride: ''

remoteCluster: false
ingressClassName: nginx

image: 
  repository: mangatasolutions/anvil
  tag: be439052d9ed89109c4dd02b387cdf7cbbcc6870

resources: {}
  # requests:
  #   cpu: 200m
  #   memory: 1Gi
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi