# Default values for anvil.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: local
domainZone: mangata.online
nameOverride: ''
envSelector: ethereum-stub
privateKey: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
remoteCluster: false
ingressClassName: nginx

dataMountPath: /data
command:
  - anvil
  - --host
  - '0.0.0.0'
  - --state
  - /data/anvil-state.json
  - --state-interval
  - '1'

enablePersistence: false
storageClass: standard
storageSize: 1Gi

image: 
  repository: mangatasolutions/anvil
  tag: be439052d9ed89109c4dd02b387cdf7cbbcc6870

resources:
  requests:
    cpu: 1
    memory: 100Mi
  limits:
    cpu: 2
    memory: 500Mi
