---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "rolllup-sequencer.name" . }}-secret"
data:
  MNEMONIC: {{ .Values.mnemonic | b64enc }}
  ETH_CHAIN_URL: {{ .Values.ethChainUrl | b64enc }}