{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  {{- include "labels" . | indent 2 }}
data:
  {{- range $key, $val := .Values.envSecrets }}
  {{ $key }}: {{ $val | b64enc | quote  }}
  {{- end }}
{{- end }}