{{- if .Values.serviceMonitor.enabled }}
################################################
# Standardized Templates - ServiceMonitor
################################################
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "name" . }}
  {{- include "labels" . | indent 2 }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
    {{- if .Values.labelsEnableDefault }}
      app.kubernetes.io/name: {{ template "name" . }}
    {{- end }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 6 }}
    {{- end }}
  endpoints:
    - port: {{ .Values.service.name }}
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- end }}
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml . | indent 6 }}
      {{- end }}
  {{- with .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- end }}
  {{- if .Values.serviceMonitor.sampleLimit }}
  sampleLimit: {{ .Values.serviceMonitor.sampleLimit }}
  {{- end }}
  
{{- end }}
