extends: semantic-release-monorepo
branches: 
  - main
  - '(gasp-node-)+([0-9])?(.{+([0-9]),x}).x'
  - name: release/next
    prerelease: rc
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - shell: bash
      # IMAGE_TAG is set from within the GHA workflow and corresponds to the image tag we want to use for the release
      publishCmd: |
        docker buildx imagetools create -t gaspxyz/rollup-node:${nextRelease.version} gaspxyz/rollup-node:${process.env.IMAGE_TAG}
        docker buildx imagetools create -t gaspxyz/rollup-node:${nextRelease.version}-fast gaspxyz/rollup-node:${process.env.IMAGE_TAG}-fast
