extends: semantic-release-monorepo
branches: 
  - main
  - '(gasp-node-)+([0-9])?(.{+([0-9]),x}).x'
  - name: release/next
    prerelease: rc
plugins:
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/release-notes-generator'
    - writerOpts:
        footerPartial: |
          {{#if noteGroups}}
          {{#each noteGroups}}
          ### {{title}}
          {{#each notes}}
          * {{text}}
          {{/each}}
          {{/each}}
          {{/if}}

          ---

          ### Docker Images
          - Standard: `gaspxyz/rollup-node:{{version}}`
          - Fast Runtime: `gaspxyz/rollup-node:{{version}}-fast`
  - - '@semantic-release/github'
    - assets:
        - 'build/**/*'
  - - '@semantic-release/exec'
    - shell: bash
      # IMAGE_TAG is set from within the GHA workflow and corresponds to the image tag we want to use for the release
      publishCmd: |
        docker buildx imagetools create -t gaspxyz/rollup-node:${nextRelease.version} gaspxyz/rollup-node:${process.env.IMAGE_TAG}
        docker buildx imagetools create -t gaspxyz/rollup-node:${nextRelease.version}-fast gaspxyz/rollup-node:${process.env.IMAGE_TAG}-fast
