name: gasp-node

services:
  node-alice:
    build:
      context: .
      args:
        ENABLE_FAST_RUNTIME: true
    image: gaspxyz/rollup-node:${ROLLUP_NODE_VERSION:-local}
    command:
      - --alith
      - --chain=rollup-local-seq
      - --base-path=/data
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --node-key=0000000000000000000000000000000000000000000000000000000000000001
      - --pruning=archive
      - --rpc-methods=unsafe
    ports:
      - 9944:9944
      - 30333:30333

  node-bob:
    build:
      context: .
      args:
        ENABLE_FAST_RUNTIME: true
    image: gaspxyz/rollup-node:${ROLLUP_NODE_VERSION:-local}
    command:
      - --baltathar
      - --chain=rollup-local-seq
      - --base-path=/data
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --bootnodes=/dns/node-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      - --pruning=archive
      - --rpc-methods=unsafe
    ports:
      - 9946:9944
