FROM debian:bookworm AS runner
ARG TARGET_DIR=target/standard-runtime/release

WORKDIR /app

COPY ${TARGET_DIR}/rollup-node /app/node
COPY ${TARGET_DIR}/wbuild/rollup-runtime/rollup_runtime.compact.compressed.wasm /app/rollup_runtime.compact.compressed.wasm

ENTRYPOINT ["/app/node"]
