repositories:
  - name: ethereum-helm-charts
    url: https://ethpandaops.github.io/ethereum-helm-charts
  - name: blockscout
    url: https://blockscout.github.io/helm-charts
  
releases:
  - name: blockscout-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.blockscoutEnabled }}
    chart: blockscout/blockscout-stack
    version: 1.6.8
    dependencies:
      - chart: oci://registry-1.docker.io/bitnamicharts/postgresql
        version: '12.x.x'
      - chart: ethereum-helm-charts/smart-contract-verifier-http
        version: '0.1.2'
    values:
      - smart-contract-verifier-http:
          enabled: true
        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 15.3.0-debian-11-r7
          pullPolicy: IfNotPresent
          auth:
            enablePostgresUser: true
            postgresPassword: postgres
            username: postgres
            password: postgres
          primary:
            extendedConfiguration: |
              max_connections = 1024
              log_min_messages = ERROR
          persistence:
            enabled: true
            size: 8Gi
        config:
          network:
            id: 1337
            name: 'Ether'
            shortname: 'Ether'
          testnet: true
          account:
            enabled: false
          prometheus:
            enabled: false
        blockscout:
          image:
            tag: 6.8.1.commit.dd6b1c9d
          env:
            RUST_LOG: warn
            DATABASE_URL: 'postgresql://postgres:postgres@blockscout-eth-postgresql:5432/blockscout?ssl=false'
            SECRET_KEY_BASE: RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5
            ETHEREUM_JSONRPC_VARIANT: 'geth'
            ETHEREUM_JSONRPC_HTTP_URL: http://evm-node-eth:8545
            ETHEREUM_JSONRPC_WS_URL: ws://evm-node-eth:8546
            ETHEREUM_JSONRPC_TRACE_URL: http://evm-node-eth:8545
            MICROSERVICE_SC_VERIFIER_ENABLED: true
            MICROSERVICE_SC_VERIFIER_URL: 'http://blockscout-eth-smart-contract-verifier-http:8050'
            MICROSERVICE_SC_VERIFIER_TYPE: sc_verifier
          ingress:
            enabled: true
            hostname: blockscout.rollup-{{ .Values.environmentName }}-eth.gasp.xyz
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: 'true'
            className: nginx
            tls:
              enabled: true
        frontend:
          enabled: true
          replicaCount: 1
          image:
            tag: v1.34.1
          ingress:
            enabled: true
            hostname: blockscout.rollup-{{ .Values.environmentName }}-eth.gasp.xyz
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: 'true'
            className: nginx
            tls:
              enabled: true
          env:
            NEXT_PUBLIC_API_PROTOCOL: https
            NEXT_PUBLIC_API_BASE_PATH: '/'
            NEXT_PUBLIC_APP_PROTOCOL: https
            NEXT_PUBLIC_HOMEPAGE_CHARTS: "[\"daily_txs\"]"
            NEXT_PUBLIC_VISUALIZE_API_HOST: https://visualizer.services.blockscout.com/
            NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: wss
            NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
            NEXT_PUBLIC_AD_TEXT_PROVIDER: 'none'
            NEXT_PUBLIC_AD_BANNER_PROVIDER: 'none'
  
  - name: blockscout-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ and .Values.blockscoutEnabled .Values.enableArbitrumServices }}
    chart: blockscout/blockscout-stack
    version: 1.6.8
    dependencies:
      - chart: oci://registry-1.docker.io/bitnamicharts/postgresql
        version: '12.x.x'
      - chart: ethereum-helm-charts/smart-contract-verifier-http
        version: '0.1.2'
    values:
      - smart-contract-verifier-http:
          enabled: true
        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 15.3.0-debian-11-r7
          pullPolicy: IfNotPresent
          auth:
            enablePostgresUser: true
            postgresPassword: postgres
            username: postgres
            password: postgres
          primary:
            extendedConfiguration: |
              max_connections = 1024
              log_min_messages = ERROR
          persistence:
            enabled: true
            size: 8Gi
        config:
          network:
            id: 1337
            name: 'Arbitrum'
            shortname: 'Arb'
          testnet: true
          account:
            enabled: false
          prometheus:
            enabled: false
        blockscout:
          image:
            tag: 6.8.1.commit.dd6b1c9d
          env:
            RUST_LOG: warn
            DATABASE_URL: 'postgresql://postgres:postgres@blockscout-arb-postgresql:5432/blockscout?ssl=false'
            SECRET_KEY_BASE: RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5
            ETHEREUM_JSONRPC_VARIANT: 'geth'
            ETHEREUM_JSONRPC_HTTP_URL: http://evm-node-arb:8545
            ETHEREUM_JSONRPC_WS_URL: ws://evm-node-arb:8546
            ETHEREUM_JSONRPC_TRACE_URL: http://evm-node-arb:8545
            MICROSERVICE_SC_VERIFIER_ENABLED: true
            MICROSERVICE_SC_VERIFIER_URL: 'http://blockscout-arb-smart-contract-verifier-http:8050'
            MICROSERVICE_SC_VERIFIER_TYPE: sc_verifier
          ingress:
            enabled: true
            hostname: blockscout.rollup-{{ .Values.environmentName }}-arb.gasp.xyz
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: 'true'
            className: nginx
            tls:
              enabled: true
        frontend:
          enabled: true
          replicaCount: 1
          image:
            tag: v1.34.1
          ingress:
            enabled: true
            hostname: blockscout.rollup-{{ .Values.environmentName }}-arb.gasp.xyz
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: 'true'
            className: nginx
            tls:
              enabled: true
          env:
            NEXT_PUBLIC_API_PROTOCOL: https
            NEXT_PUBLIC_API_BASE_PATH: '/'
            NEXT_PUBLIC_APP_PROTOCOL: https
            NEXT_PUBLIC_HOMEPAGE_CHARTS: "[\"daily_txs\"]"
            NEXT_PUBLIC_VISUALIZE_API_HOST: https://visualizer.services.blockscout.com/
            NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: wss
            NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
            NEXT_PUBLIC_AD_TEXT_PROVIDER: 'none'
            NEXT_PUBLIC_AD_BANNER_PROVIDER: 'none'