apiVersion: v1
kind: Service
metadata:
  name: {{ include "anvil.name" . }}
  {{- if .Values.remoteCluster }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ include "anvil.name" . }}-{{ .Values.environment }}.{{ .Values.domainZone }}"
  {{- end }}
  labels: {{- include "anvil.labels" . | nindent 4 }}
    service: {{ include "anvil.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8545
      name: rpc
  selector:
    {{- include "anvil.selectorLabels" . | nindent 4 }}
    service: {{ include "anvil.name" . }}
