apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "anvil.name" . }}
  labels: {{- include "anvil.labels" . | nindent 4 }}
    service: {{ include "anvil.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "anvil.selectorLabels" . | nindent 6 }}
      service: {{ include "anvil.name" . }}
  serviceName: {{ include "anvil.name" . }}
  template:
    metadata:
      labels:
        {{- include "anvil.labels" . | nindent 8 }}
        service: {{ include "anvil.name" . }}
    spec:
      initContainers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          env:
            - name: ENV_SELECTOR
              value: {{ .Values.envSelector }}
          args:
            - -c
            - |
              set -ex
              # Start anvil to dump the state
              anvil --dump-state {{ .Values.dataMountPath }}/anvil-state.json &

              # anvil needs some time to spin up or it will fail to dump the state correctly for arbitrum
              sleep 5

              # Deploy all contracts
              forge script script/MultiStage.s.sol \
                --rpc-url http://localhost:8545 \
                --private-key {{ .Values.privateKey }} \
                --broadcast -v

              # Stop anvil
              pkill anvil
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.dataMountPath }}
              name: data
      containers:
        - name: anvil
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: {{ toYaml .Values.command | nindent 12 }}
          ports:
            - containerPort: 8545
              name: rpc
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.dataMountPath }}
              name: data
      {{- if not .Values.enablePersistence }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.enablePersistence }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: {{ .Values.storageClass }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.storageSize }}
  {{- end }}
