{{ $name :=  "anvil" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels: {{- include "anvil.labels" . | nindent 4 }}
    service: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "anvil.selectorLabels" . | nindent 6 }}
      service: {{ $name }}
  serviceName: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "anvil.labels" . | nindent 8 }}
        service: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ .Values.image | quote }}
          ports:
            - containerPort: 8545
              name: rpc
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "anvil.name" . }}-configmap
