services:
  sequencer-eth:
    restart: unless-stopped
    image: mangatasolutions/rollup-sequencer:${ROLLUP_SEQUENCER_VERSION:-local}
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    build: .
    environment:
      MANGATA_NODE_URL: ${ROLLUP_SEQUENCER_MANGATA_NODE_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ROLLUP_SEQUENCER_ETH_CHAIN_URL_ETH:-wss://ethereum.publicnode.com}
      MANGATA_CONTRACT_ADDRESS: ${MANGATA_CONTRACT_ADDRESS:-0x0355B7B8cb128fA5692729Ab3AAa199C1753f726}
      MNEMONIC: ${ROLLUP_SEQUENCER_MNEMONIC_ETH:-'//Bob'}
      BLOCK_NUMBER_DELAY: ${ROLLUP_SEQUENCER_BLOCK_NUMBER_DELAY}
      L1_CHAIN: ${ROLLUP_SEQUENCER_L1_CHAIN_ETH:-Ethereum}

  sequencer-arb:
    restart: unless-stopped
    image: mangatasolutions/rollup-sequencer:${ROLLUP_SEQUENCER_VERSION:-local}
    depends_on:
      arbitrum-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    build: .
    environment:
      MANGATA_NODE_URL: ${ROLLUP_SEQUENCER_MANGATA_NODE_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ROLLUP_SEQUENCER_ETH_CHAIN_URL_ARB:-wss://ethereum.publicnode.com}
      MANGATA_CONTRACT_ADDRESS: ${MANGATA_CONTRACT_ADDRESS:-0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9}
      MNEMONIC: ${ROLLUP_SEQUENCER_MNEMONIC_ARB:-'//Bob'}
      BLOCK_NUMBER_DELAY: ${ROLLUP_SEQUENCER_BLOCK_NUMBER_DELAY}
      L1_CHAIN: ${ROLLUP_SEQUENCER_L1_CHAIN_ARB:-Arbitrum}
