services:
  sequencer:
    image: mangatasolutions/rollup-sequencer:local
    depends_on:
      rolldown:
        condition: service_completed_successfully
      parachain-2110-0:
        condition: service_started
    build: .
    environment:
      MANGATA_URL: ${ROLLUP_SEQUENCER_MANGATA_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ROLLUP_SEQUENCER_ETH_CHAIN_URL:-wss://ethereum.publicnode.com}
      MANGATA_CONTRACT_ADDRESS: "0x5f3f1dbd7b74c6b46e8c44f98792a1daf8d69154"
      MNEMONIC: ${ROLLUP_SEQUENCER_MNEMONIC:-'//Alice'}
