# Default values for rollup-sequencer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: local
command: []
args: []

# Randomly generated key, should not be used for anything
mnemonic: 'some mnemonic'
ethChainUrl: wss://ethereum.publicnode.com
## Environment variables
env:
  MANGATA_URL: wss://collator-01-ws-rococo.mangata.online
  MANGATA_CONTRACT_ADDRESS: "0x5f3f1dbd7b74c6b46e8c44f98792a1daf8d69154"

nameOverride: ""

image:
  repository: mangatasolutions/rollup-sequencer
  pullPolicy: Always
  ## Overrides the image tag whose default is the chart appVersion.
  tag: latest

resources:
  {}
  # requests:
  #   cpu: 200m
  #   memory: 1Gi
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi

# -- Define which Nodes the Pods are scheduled on
nodeSelector: {}
# -- Grace termination period of the Pod
terminationGracePeriodSeconds: 60
# -- Tolerations for use with node taints
tolerations: []
# -- Assign custom affinity rules
affinity: {}

podAnnotations:
  {}
  # 'fluentbit.io/parser': 'substrate'
