repositories:
  - name: mangata-node
    url: git+https://github.com/gasp-xyz/helm-charts@charts?ref=node-v2.3.0

helmDefaults:
  kubeContext: '{{ .Values.kubeContext }}'

releases:
  - name: collator-01
    installed: {{ .Values.collatorsEnabled }}
    chart: mangata-node/node
    namespace: 'rollup-{{ .Values.environmentName }}'
    values:
      - image:
          repository: {{ .Values.collator.image.repository | quote }}
          tag: {{ .Values | get "collator.image.tag" (requiredEnv "IMAGE_TAG") | quote }}
        environment: 'rollup-{{ .Values.environmentName }}'
        chain: {{ .Values | getOrNil "collator.chain" }}
        disableChainspecGeneration: {{ .Values | getOrNil "collator.disableChainspecGeneration" }}
        customChainspecUrl: {{ .Values | get "collator.customChainspecUrl" "" }}
        domainZone: gasp.xyz
        command: '/app/node'
        isParachain: false
        isCollator: false
        role: collator
        remoteCluster: {{ .Values.remoteCluster }}
        wsHealthExporter: {{ .Values.collator.wsHealthExporter | toYaml | nindent 10 }}
        enableServiceMonitorCollectors: {{ .Values.collator.enableServiceMonitorCollectors }}
        storageClass: {{ .Values.collator.storageClass | quote }}
        storageSize: {{ .Values.collator.storageSize | quote }}
        resources: {{ .Values | getOrNil "collator.resources" | toYaml | nindent 10 }}
        tolerations: {{ .Values | getOrNil "collator.tolerations" | toYaml | nindent 10 }}
        # collator-01 specific configs
        nodeSelector: {{ .Values | getOrNil "collator.collator01.nodeSelector" | toYaml | nindent 10 }}
        customNodeKey: {{ .Values.collator.collator01.customNodeKey }}
        bootnodeAddr: {{ .Values.collator.collator01.bootnodeAddr }}
        extraArgs: {{ .Values.collator.collator01.extraArgs | toYaml | nindent 10 }}
        accountKeys: {{ .Values | getOrNil "collator.collator01.accountKeys" | toYaml | nindent 10 }}
  
  - name: collator-02
    installed: {{ .Values.collatorsEnabled }}
    chart: mangata-node/node
    namespace: 'rollup-{{ .Values.environmentName }}'
    values:
      - image:
          repository: {{ .Values.collator.image.repository | quote }}
          tag: {{ .Values | get "collator.image.tag" (requiredEnv "IMAGE_TAG") | quote }}
        environment: 'rollup-{{ .Values.environmentName }}'
        chain: {{ .Values | getOrNil "collator.chain" }}
        disableChainspecGeneration: {{ .Values | getOrNil "collator.disableChainspecGeneration" }}
        customChainspecUrl: {{ .Values | get "collator.customChainspecUrl" "" }}
        domainZone: gasp.xyz
        command: '/app/node'
        isParachain: false
        isCollator: false
        role: collator
        remoteCluster: {{ .Values.remoteCluster }}
        wsHealthExporter: {{ .Values.collator.wsHealthExporter | toYaml | nindent 10 }}
        enableServiceMonitorCollectors: {{ .Values.collator.enableServiceMonitorCollectors }}
        storageClass: {{ .Values.collator.storageClass | quote }}
        storageSize: {{ .Values.collator.storageSize | quote }}
        resources: {{ .Values | getOrNil "collator.resources" | toYaml | nindent 10 }}
        tolerations: {{ .Values | getOrNil "collator.tolerations" | toYaml | nindent 10 }}
        # collator-02 specific configs
        nodeSelector: {{ .Values | getOrNil "collator.collator02.nodeSelector" | toYaml | nindent 10 }}
        customNodeKey: {{ .Values.collator.collator02.customNodeKey }}
        bootnodeAddr: {{ .Values.collator.collator02.bootnodeAddr }}
        extraArgs: {{ .Values.collator.collator02.extraArgs | toYaml | nindent 10 }}
        accountKeys: {{ .Values | getOrNil "collator.collator02.accountKeys" | toYaml | nindent 10 }}
