name: CI

on:
  push:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.x
          check-latest: true
          cache: pip

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "1.9.5"
          cache: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Python dependencies
        run: |
          pip install -U setuptools
          pip install -r requirements.txt

      - name: Build contracts
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Format contracts
        if: false
        run: bun run format
        id: format

      - name: Lint contracts
        if: false
        run: bun run lint
        id: lint

      - name: Run unit tests
        run: forge test -vvv --fail-fast
        id: test

      - name: Analyze contracts with static analyzer
        if: false
        run: bun run analyze:ci
        id: analyze

      - name: Create gas snapshot
        run: NO_COLOR=1 forge snapshot >> $GITHUB_STEP_SUMMARY
        id: snapshot
