remoteCluster: true

blockscoutEnabled: true
enableArbitrumServices: true

####################
# evm-node configs #
####################
evmNode:
  enabled: true
  customGenesisUrlEth: "https://raw.githubusercontent.com/mangata-finance/eigen-layer-monorepo/main/contracts/script/config/holesky-stub.json"
  customGenesisUrlArb: "https://raw.githubusercontent.com/mangata-finance/eigen-layer-monorepo/main/contracts/script/config/arbitrum-sepolia-stub.json"

#####################
# collator configs #
#####################
collatorsEnabled: true
collatorRpcNodesEnabled: false
collator:
  image:
    repository: mangatasolutions/rollup-node
    tag: 3a07824d8b8a6ad027424629b814a5edb61654cf
  disableChainspecGeneration: true
  customChainspecUrl: https://raw.githubusercontent.com/gasp-xyz/chainspec/0c05b37addc49e807a7802604e9648691bfe2a9a/rollup-dev-env-chainspecs/rollup-frontend-4d76522-chainspec-raw.json
  enableServiceMonitorCollectors: true
  storageClass: node-data-volume-retain
  storageSize: 50Gi
  wsHealthExporter:
    enabled: true
    image: paritytech/ws-health-exporter:bc071a44-20230830
    env:
      WSHE_NODE_MIN_PEERS: 2
  resources:
    limits:
      cpu: "4"
      memory: 12Gi
    requests:
      cpu: "4"
      memory: 12Gi
  tolerations:
    - key: production
      operator: Equal
      value: "true"
      effect: NoSchedule
  collator01:
    # Identity ID: 12D3KooWJCggfzsr6LAdXSdfgFLxsMtgCq9qSq79vqYtdG2oT8Za
    customNodeKey: "a9a20a5fa298fdd68ae5516c60c060c419e37bae4440d6f52ae3439162522fa2"
    bootnodeAddr: /dns/collator-02-p2p/tcp/30333/p2p/12D3KooWB7YXuwmv55wy5UFDe9yRGYJFPk1r3DpFMSyFx5KqMi3G
    extraArgs:
      - --alith
      - --pruning=archive
    nodeSelector:
      production: "true"
  collator02:
    # Identity ID: 12D3KooWB7YXuwmv55wy5UFDe9yRGYJFPk1r3DpFMSyFx5KqMi3G
    customNodeKey: "bf08651f3aa5b9fed7ce2e82a5fce8c31f1889e93e3019476b3052f33d57116f"
    bootnodeAddr: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWJCggfzsr6LAdXSdfgFLxsMtgCq9qSq79vqYtdG2oT8Za
    extraArgs:
      - --baltathar
      - --pruning=archive
    nodeSelector:
      production: "true"

######################
# aggregator configs #
######################
aggregatorEnabled: true
# tests/keys/aggregator.ecdsa.key.json
aggregatorEnvSecrets:
  ECDSA_KEY_JSON: '{"address":"a0ee7a142d267c1f36714e4a8f75612f20a79720","crypto":{"cipher":"aes-128-ctr","ciphertext":"b0f6f8e3ba33f0b382b080de6661d827181de480f1a4f94bc20d66cb3d585907","cipherparams":{"iv":"4e3f9a8ca6ef8d1cd408e8aaae3c22d2"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c8f9f8cc03913e09cee7e1fd68732fac327576203ab277d740270f1dea82ee7e"},"mac":"353d65850b20d5fdb90ca2385c52e5b57662cb1d906fd58143f20a7720723cf6"},"id":"d3036cc7-d068-4f2f-9667-60aaca660e61","version":3}'
aggregatorEnv:
  # rpc
  ETH_RPC_URL: http://evm-node-eth:8545
  ETH_WS_URL: ws://evm-node-eth:8546
  # contracts
  CHAIN_ID: "1337"
  AVS_REGISTRY_COORDINATOR_ADDR: 0x851356ae760d987E095750cCeb3bC6014560891C
  # AVS
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_BLOCK_VALIDATION_PERIOD: "5"
  # OP
  ECDSA_EPHEMERAL_KEY: "true"
  BLS_EPHEMERAL_KEY: "true"
  AVS_KICK_PERIOD: 5
  AVS_MIN_OP_UPDATE_INTERVAL: 1

#####################
# finalizer configs #
#####################
finalizerEnabled: true
finalizerEnvSecrets: {}
finalizerEnv:
  # rpc
  ETH_RPC_URL: http://evm-node-eth:8545
  ETH_WS_URL: ws://evm-node-eth:8546
  # contracts
  CHAIN_ID: "1337"
  AVS_REGISTRY_COORDINATOR_ADDR: 0x851356ae760d987E095750cCeb3bC6014560891C
  # OP
  RUST_LOG: info,substrate=warn
  AVS_RPC_URL: http://avs-aggregator:8090
  ECDSA_EPHEMERAL_KEY: "true"
  BLS_EPHEMERAL_KEY: "true"
  # rollup-node configs
  ROLLUP_NODE_CHAIN: /app/frontend-chainspec.json
  ROLLUP_NODE_BOOTNODE: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWJCggfzsr6LAdXSdfgFLxsMtgCq9qSq79vqYtdG2oT8Za

###########################
# rollup-updater configs #
###########################
updaterEnabled: true

updaterChainUrlEth: ws://evm-node-eth:8546
updaterMnemonicEth: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
updaterEnvEth:
  CHAIN: "reth-1337"
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  EIGEN_CONTRACT_ADDRESS: "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
  MANGATA_CONTRACT_ADDRESS: "0x7bc06c482DEAd17c0e297aFbC32f6e63d3846650"
  FINALIZATION_SOURCE: "relay"

updaterChainUrlArb: ws://evm-node-arb:8546
updaterMnemonicArb: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
updaterEnvArb:
  CHAIN: "reth-31337"
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  EIGEN_CONTRACT_ADDRESS: "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  FINALIZATION_SOURCE: "relay"

############################
# rollup-sequencer configs #
############################
sequencerEnabled: true
secondSequencerEnabled: false

firstSequencerMnemonicEth: "0x8075991ce870b93a8870eca0c0f91913d12f47948ca0fd25b49c6fa7cdbeee8b"
secondSequencerMnemonicEth: "bottom drive obey lake curtain smoke basket hold race lonely fit walk//Bob"
sequencerChainUrlEth: ws://evm-node-eth:8546
sequencerEnvEth:
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc"

firstSequencerMnemonicArb: "0x0b6e18cafb6ed99687ec547bd28139cafdd2bffe70e6b688025de6b445aa5c5b"
secondSequencerMnemonicArb: "bottom drive obey lake curtain smoke basket hold race lonely fit walk//Bob"
sequencerChainUrlArb: ws://evm-node-arb:8546
sequencerEnvArb:
  CHAIN: "reth"
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
