finalizerEnableServiceMonitorCollectors: true
remoteCluster: true


blockscoutEnabled: true
secondFinalizerEnabled: true
secondSequencerEnabled: true


#####################
# collator configs #
#####################
collatorsEnabled: true
collator:
  image:
    tag: b6f5f6c13ff851bfdfb36d01e0d8d67fe7c5bcc9
  chain: ''
  customChainspecUrl: https://raw.githubusercontent.com/mangata-finance/chainspec/master/rollup-local-fd0e82a316c1f0f940211ca76b7de541d6f7689a-raw.json
  wsHealthExporter:
    enabled: true
    image: paritytech/ws-health-exporter:bc071a44-20230830
    env:
      WSHE_NODE_MIN_PEERS: 2
  enablePodMonitoringCollectors: true
  enableServiceMonitorCollectors: true
  storageClass: node-data-volume-retain
  storageSize: 50Gi
  tolerations:
    - key: production
      operator: Equal
      value: 'true'
      effect: NoSchedule
  nodeSelector:
    production: 'true'
