remoteCluster: true
blockscoutEnabled: false
enableArbitrumServices: true
enableBaseServices: true
##################################
# contracts && evm-node configs #
##################################
# contractsImageTag:''
evmNode:
  enabled: false
#####################
# collator configs #
#####################
collatorsEnabled: true
collatorRpcNodesEnabled: true
collatorRpcNodesEnableSharedDnsRecord: true
collator:
  resources:
    requests:
      cpu: 6
      memory: 12Gi
    limits:
      cpu: 6
      memory: 12Gi
  image:
    repository: gaspxyz/rollup-node
    # Ref: https://github.com/gasp-xyz/mangata-node/tree/3722076d06f7c1ff7c727a799260c5df2a5eb62f
    tag: 80ae4fbab12eb41980d8d38b4f860f0a48ee3af8
  disableChainspecGeneration: true
  customChainspecUrl: https://raw.githubusercontent.com/gasp-xyz/chainspec/5b0100d05c4744f31af56105bce3151f8cbc2d15/rollup-dev-env-chainspecs/holesky-62fa181-raw.json
  enableServiceMonitorCollectors: true
  storageClass: node-data-volume-retain
  storageSize: 150Gi
  wsHealthExporter:
    enabled: true
    image: paritytech/ws-health-exporter:bc071a44-20230830
    env:
      WSHE_NODE_MIN_PEERS: 2
  tolerations:
    - key: production
      operator: Equal
      value: "true"
      effect: NoSchedule
  # Node specific collator configs
  collator01:
    # Identity ID: 12D3KooWPZ4S8zcLcsLBRSeqbbh233tFWgc6hRtXTce9x1EuLuWL
    customNodeKey: "a7633d78f1d366ab788efc12af026ca43f1cf5e2865334f9bdf5b5d1b9a2c417"
    bootnodeAddr: /dns/collator-02-p2p/tcp/30333/p2p/12D3KooWCeV5mfZ9qig6c23vngjxQKyq1GJHBFN3DJNMkYqG2cbT
    accountKeys:
      - type: aura
        scheme: sr25519
        seed: ref+sops://secrets.enc.yaml#/holeskyCollator01AuraKey
      - type: gran
        scheme: ed25519
        seed: ref+sops://secrets.enc.yaml#/holeskyCollator01GrandpaKey
    extraArgs:
      - --validator
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      production: "true"
      topology.kubernetes.io/zone: europe-west1-b
  collator02:
    # Identity ID: 12D3KooWCeV5mfZ9qig6c23vngjxQKyq1GJHBFN3DJNMkYqG2cbT
    customNodeKey: "dc81e44431fcebce274e2d3e33137f54a229edc595ba2bd37aee480b1da6d005"
    bootnodeAddr: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWPZ4S8zcLcsLBRSeqbbh233tFWgc6hRtXTce9x1EuLuWL
    accountKeys:
      - type: aura
        scheme: sr25519
        seed: ref+sops://secrets.enc.yaml#/holeskyCollator02AuraKey
      - type: gran
        scheme: ed25519
        seed: ref+sops://secrets.enc.yaml#/holeskyCollator02GrandpaKey
    extraArgs:
      - --validator
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      production: "true"
      topology.kubernetes.io/zone: europe-west1-c
  rpc01:
    bootnodeAddr: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWPZ4S8zcLcsLBRSeqbbh233tFWgc6hRtXTce9x1EuLuWL
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-b
  rpc02:
    bootnodeAddr: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWPZ4S8zcLcsLBRSeqbbh233tFWgc6hRtXTce9x1EuLuWL
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-c
  rpc03:
    bootnodeAddr: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWPZ4S8zcLcsLBRSeqbbh233tFWgc6hRtXTce9x1EuLuWL
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-b
######################
# aggregator configs #
######################
aggregatorEnabled: true
aggregatorImageTag: 80ae4fbab12eb41980d8d38b4f860f0a48ee3af8

aggregatorEnvSecrets:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/testnetAggregatorEcdsaKeyJson
  ECDSA_KEY_PASSWORD: ref+sops://secrets.enc.yaml#/testnetAggregatorEcdsaKeyPassword
  ETH_RPC_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
  ETH_WS_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
aggregatorEnv:
  SUBSTRATE_RPC_URL: wss://collator-01-ws-rollup-holesky-v3.gasp.xyz
  CHAIN_ID: "17000"
  AVS_BLOCK_VALIDATION_PERIOD: "100"
  AVS_DEBOUNCE_RPC: "20"
  AVS_DEPLOYMENT_BLOCK: "2884411"
  AVS_KICK_PERIOD: "25"
  AVS_REGISTRY_COORDINATOR_ADDR: "0xef5Ea04287c2BCd0A984563B055f39e650dF0e28"
  AVS_RPC_URL: http://avs-aggregator:8090
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_TASK_EXPIRATION: "300"
  AVS_UPDATE_STAKE_PERIOD: "150"
  OPT_IN_AT_STARTUP: "true"
  LOG_LEVEL: "info"
  RUST_LOG: avs=debug
  AGG_IDLE_START: false
  AGG_RUN_TRIGGER_API_KEY: "secrettoken"
#####################
# gaspAvs configs #
#####################
gaspAvsEnabled: true
gaspAvsImageTag: 80ae4fbab12eb41980d8d38b4f860f0a48ee3af8

gaspAvsData:
  storageClass: node-data-volume-retain
  mountPath: /data
  storageSize: 150Gi
gaspAvsEnvSecrets:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/testnetFinalizerEcdsaKeyJson
  ECDSA_KEY_PASSWORD: ref+sops://secrets.enc.yaml#/testnetFinalizerEcdsaKeyPassword
  BLS_KEY_JSON: ref+sops://secrets.enc.yaml#/testnetFinalizerBlsKeyJson
  BLS_KEY_PASSWORD: ref+sops://secrets.enc.yaml#/testnetFinalizerBlsKeyPassword
  ETH_RPC_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
  ETH_WS_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
gaspAvsEnv:
  CHAIN_ID: "17000"
  AVS_BLOCK_VALIDATION_PERIOD: "100"
  AVS_DEBOUNCE_RPC: "20"
  AVS_DEPLOYMENT_BLOCK: "2884411"
  AVS_KICK_PERIOD: "25"
  AVS_REGISTRY_COORDINATOR_ADDR: "0xef5Ea04287c2BCd0A984563B055f39e650dF0e28"
  AVS_RPC_URL: http://avs-aggregator:8090
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_TASK_EXPIRATION: "300"
  AVS_UPDATE_STAKE_PERIOD: "150"
  OPT_IN_AT_STARTUP: "true"
  LOG_LEVEL: "info"
  RUST_LOG: avs=debug,ether=trace
  TESTNET: "false"
  # rollup-node configs
  ROLLUP_NODE_BOOTNODE: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWPZ4S8zcLcsLBRSeqbbh233tFWgc6hRtXTce9x1EuLuWL
  ROLLUP_NODE_CUSTOM_CHAINSPEC_URL: https://raw.githubusercontent.com/gasp-xyz/chainspec/5b0100d05c4744f31af56105bce3151f8cbc2d15/rollup-dev-env-chainspecs/holesky-62fa181-raw.json
###########################
# updater configs #
###########################
updaterEnabled: true
updaterImageTag: 80ae4fbab12eb41980d8d38b4f860f0a48ee3af8
updaterEnvSecrets:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/arbitrumSepoliaUpdaterEcdsaKeyJson
  ROOT_ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/arbitrumSepoliaUpdaterRootEcdsaKeyJson
  SOURCE_RPC_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
  SOURCE_WS_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
  TARGET_RPC_URL: ref+sops://secrets.enc.yaml#/arbitrumSepoliaHttpsUrl
  TARGET_WS_URL: ref+sops://secrets.enc.yaml#/arbitrumSepoliaWssUrl
updaterEnv:
  SOURCE_CHAIN_ID: 17000
  TARGET_CHAIN_ID: 421614
  TARGET_CHAIN_INDEX: 1
  AVS_REGISTRY_COORDINATOR_ADDR: 0xef5Ea04287c2BCd0A984563B055f39e650dF0e28
  GASP_SERVICE_ADDR: 0x710E31ce9950483f47c80EA2655143dbA5bA3374
  TESTNET: "false"
  PUSH_FIRST_INIT: "true"
  REINIT: "false"
updaterEnvSecretsBase:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/baseSepoliaUpdaterEcdsaKeyJson
  ROOT_ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/baseSepoliaUpdaterRootEcdsaKeyJson
  SOURCE_RPC_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
  SOURCE_WS_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
  TARGET_RPC_URL: ref+sops://secrets.enc.yaml#/baseSepoliaHttpsUrl
  TARGET_WS_URL: ref+sops://secrets.enc.yaml#/baseSepoliaWssUrl
updaterEnvBase:
  SOURCE_CHAIN_ID: 17000
  TARGET_CHAIN_ID: 84532
  TARGET_CHAIN_INDEX: 2
  AVS_REGISTRY_COORDINATOR_ADDR: 0xef5Ea04287c2BCd0A984563B055f39e650dF0e28
  GASP_SERVICE_ADDR: 0x80A15DbBE2f2b6E2A28aEbbE9cB0a038DC0be64e
  TESTNET: "false"
  PUSH_FIRST_INIT: "true"
  REINIT: "false"
############################
# sequencer configs #
############################
sequencerEnabled: true
# Override the image tag provided on deployment from IMAGE_TAG env variable
sequencerImageTag: 80ae4fbab12eb41980d8d38b4f860f0a48ee3af8

sequencerEnvEth:
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x34B38Fd98aBE38B52258253fb4E1D0F5EFF26343"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsEth:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/holeskySequencerPrivateKey
  MNEMONIC: ref+sops://secrets.enc.yaml#/holeskySequencerPrivateKey
sequencerEnvArb:
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x18Ef4858e5581d20c2145ea0dFEA7F4d81A957A5"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsArb:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumSepoliaWssUrl
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/arbitrumSepoliaSequencerPrivateKey
  MNEMONIC: ref+sops://secrets.enc.yaml#/arbitrumSepoliaSequencerPrivateKey
sequencerEnvBase:
  L1_CHAIN: "Base"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x2215C253202504a42723B46fe72D1Bb61B3b1918"
  LIMIT: "100"
  WATCHDOG: 30
sequencerEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseSepoliaWssUrl
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/baseSepoliaSequencerPrivateKey
  MNEMONIC: ref+sops://secrets.enc.yaml#/baseSepoliaSequencerPrivateKey
#########################
# ferry-deposit configs #
#########################
ferryDepositEnabled: false
ferryDepositImageTag: 80ae4fbab12eb41980d8d38b4f860f0a48ee3af8
ferryDepositEnvEth:
  MANGATA_NODE_URL: wss://collator-01-ws-rollup-holesky-v3.gasp.xyz
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
  MANGATA_CONTRACT_ADDRESS: "0x34B38Fd98aBE38B52258253fb4E1D0F5EFF26343"
  L1_CHAIN: "Ethereum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 0
  LOG: silly
ferryDepositEnvSecretsEth:
  MNEMONIC: ref+sops://secrets.enc.yaml#/holeskyFerryDepositPrivateKey
ferryDepositEnvArb:
  MANGATA_NODE_URL: wss://collator-01-ws-rollup-holesky-v3.gasp.xyz
  MANGATA_CONTRACT_ADDRESS: "0x18Ef4858e5581d20c2145ea0dFEA7F4d81A957A5"
  L1_CHAIN: "Arbitrum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 0
  LOG: silly
ferryDepositEnvSecretsArb:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumSepoliaWssUrl
  MNEMONIC: ref+sops://secrets.enc.yaml#/arbitrumSepoliaFerryDepositPrivateKey
ferryDepositEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x2215C253202504a42723B46fe72D1Bb61B3b1918"
  L1_CHAIN: "Base"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 0
  LOG: silly
ferryDepositEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseSepoliaWssUrl
  MNEMONIC: ref+sops://secrets.enc.yaml#/baseSepoliaFerryDepositPrivateKey
############################
# ferry-withdrawal configs #
############################
ferryWithdrawalEnabled: false
ferryWithdrawalImageTag: 80ae4fbab12eb41980d8d38b4f860f0a48ee3af8
ferryWithdrawalEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
  MANGATA_CONTRACT_ADDRESS: "0x34B38Fd98aBE38B52258253fb4E1D0F5EFF26343"
  L1_CHAIN: "holesky"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
ferryWithdrawalEnvSecretsEth:
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/holeskyFerryWithdrawalPrivateKey
ferryWithdrawalEnvArb:
  MANGATA_NODE_URL: wss://collator-01-ws-rollup-holesky-v3.gasp.xyz
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumSepoliaWssUrl
  MANGATA_CONTRACT_ADDRESS: 0x18Ef4858e5581d20c2145ea0dFEA7F4d81A957A5
  L1_CHAIN: "arbitrum-sepolia"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
ferryWithdrawalEnvSecretsArb:
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/arbitrumSepoliaFerryWithdrawalPrivateKey
ferryWithdrawalEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x2215C253202504a42723B46fe72D1Bb61B3b1918"
  L1_CHAIN: "base-sepolia"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
ferryWithdrawalEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseSepoliaWssUrl
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/baseSepoliaFerryWithdrawalPrivateKey
########################
# closer configs #
########################
closerEnabled: true
closerImageTag: 612242d8acb1ebe086c1508d2d015653f7d1fffc
closerEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x34B38Fd98aBE38B52258253fb4E1D0F5EFF26343"
  L1_CHAIN: "holesky"
  TOKENS_TO_TRACK: '[["0x0000000000000000000000000000000000000000", 1, 1]]'
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  BATCH_SIZE: 50
  STASH_URL: https://gasp-stash-holesky-dot-direct-pixel-353917.oa.r.appspot.com/
closerEnvSecretsEth:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/holeskyCloserPrivateKey
closerEnvArb:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x18Ef4858e5581d20c2145ea0dFEA7F4d81A957A5"
  L1_CHAIN: "arbitrum-sepolia"
  TOKENS_TO_TRACK: '[["0x0000000000000000000000000000000000000000", 1, 1]]'
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  BATCH_SIZE: 50
  STASH_URL: https://gasp-stash-holesky-dot-direct-pixel-353917.oa.r.appspot.com/
closerEnvSecretsArb:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumSepoliaWssUrl
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/arbitrumSepoliaCloserPrivateKey
closerEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x2215C253202504a42723B46fe72D1Bb61B3b1918"
  L1_CHAIN: "base-sepolia"
  TOKENS_TO_TRACK: '[["0x0000000000000000000000000000000000000000", 1, 1]]'
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  BATCH_SIZE: 50
  STASH_URL: https://gasp-stash-holesky-dot-direct-pixel-353917.oa.r.appspot.com/
closerEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseSepoliaWssUrl
  PRIVATE_KEY: ref+sops://secrets.enc.yaml#/baseSepoliaCloserPrivateKey
