remoteCluster: true

blockscoutEnabled: false
enableArbitrumServices: true
enableBaseServices: true

####################
# evm-node configs #
####################
evmNode:
  enabled: false

#####################
# collator configs #
#####################
collatorsEnabled: true
collatorRpcNodesEnabled: true
collatorRpcNodesEnableSharedDnsRecord: true
collator:
  resources:
    requests:
      cpu: 6
      memory: 12Gi
    limits:
      cpu: 6
      memory: 12Gi
  image:
    repository: mangatasolutions/rollup-node
    # Ref: https://github.com/gasp-xyz/mangata-node/tree/3722076d06f7c1ff7c727a799260c5df2a5eb62f
    tag: f26183b4e1055ff700c0b7b4483616473508ddb9
  disableChainspecGeneration: true
  customChainspecUrl: https://raw.githubusercontent.com/gasp-xyz/chainspec/f9604551934c498a6a814d84f2cd6c01803d24d7/rollup-dev-env-chainspecs/alpha-launch-f26183b-raw.json
  enableServiceMonitorCollectors: true
  storageClass: node-data-volume-retain
  storageSize: 150Gi
  wsHealthExporter:
    enabled: true
    image: paritytech/ws-health-exporter:bc071a44-20230830
    env:
      WSHE_NODE_MIN_PEERS: 2
  # Node specific collator configs
  collator01:
    # Identity ID: 12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo
    customNodeKey: ref+sops://secrets.enc.yaml#/rollupProdCollator01CustomNodeKey
    bootnodeAddr: /dns4/collator-02-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWFGDFJken9CfwP1WRQ9MDANskcfZCeAVHTpE6utdhHM6Y
    accountKeys:
      - type: aura
        scheme: sr25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-01-aura-key-seed
      - type: gran
        scheme: ed25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-01-grandpa-key-seed
    extraArgs:
      - --validator
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-b
  collator02:
    # Identity ID: 12D3KooWFGDFJken9CfwP1WRQ9MDANskcfZCeAVHTpE6utdhHM6Y
    customNodeKey: ref+sops://secrets.enc.yaml#/rollupProdCollator02CustomNodeKey
    bootnodeAddr: /dns4/collator-01-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo
    accountKeys:
      - type: aura
        scheme: sr25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-02-aura-key-seed
      - type: gran
        scheme: ed25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-02-grandpa-key-seed
    extraArgs:
      - --validator
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-c
  collator03:
    enabled: true
    # Identity ID: 12D3KooWMG7Benq1sMjRzgf1wATin9t61Rt88LuE1a5exx5WcPm9
    customNodeKey: ref+sops://secrets.enc.yaml#/rollupProdCollator03CustomNodeKey
    bootnodeAddr: /dns4/collator-01-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo
    accountKeys:
      - type: aura
        scheme: sr25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-03-aura-key-seed
      - type: gran
        scheme: ed25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-03-grandpa-key-seed
    extraArgs:
      - --validator
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-b
  collator04:
    enabled: true
    # Identity ID: 12D3KooWDq43eHqWDhW4J1gZpDuQDxUCKirD3sQvyjp9m5udxiEN
    customNodeKey: ref+sops://secrets.enc.yaml#/rollupProdCollator04CustomNodeKey
    bootnodeAddr: /dns4/collator-01-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo
    accountKeys:
      - type: aura
        scheme: sr25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-04-aura-key-seed
      - type: gran
        scheme: ed25519
        seed: ref+gcpsecrets://direct-pixel-353917/rollup-prod-collator-04-grandpa-key-seed
    extraArgs:
      - --validator
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-c
  rpc01:
    bootnodeAddr: /dns4/collator-01-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-b
  rpc02:
    bootnodeAddr: /dns4/collator-01-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-c
  rpc03:
    bootnodeAddr: /dns4/collator-01-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo
    nodeSelector:
      topology.kubernetes.io/zone: europe-west1-b

######################
# aggregator configs #
######################
aggregatorEnabled: false
# Override the image tag provided on deployment from IMAGE_TAG env variable
# aggregatorImageTag: 5d6f2a4db68e0601f14b3ced43773488efdda164

aggregatorEnvSecrets:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/testnetAggregatorEcdsaKeyJson
  ECDSA_KEY_PASSWORD: ref+sops://secrets.enc.yaml#/testnetAggregatorEcdsaKeyPassword
  ETH_RPC_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
  ETH_WS_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
aggregatorEnv:
  SUBSTRATE_RPC_URL: ws://collator-01:9944
  CHAIN_ID: "17000"
  AVS_BLOCK_VALIDATION_PERIOD: "100"
  AVS_DEBOUNCE_RPC: "20"
  AVS_DEPLOYMENT_BLOCK: "1233400"
  AVS_KICK_PERIOD: "25"
  AVS_REGISTRY_COORDINATOR_ADDR: "0xfd6A45621DDfeBF94C082e60E0De92aA305a97a1"
  AVS_RPC_URL: http://avs-aggregator:8090
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_TASK_EXPIRATION: "300"
  AVS_UPDATE_STAKE_PERIOD: "150"
  OPT_IN_AT_STARTUP: "true"
  LOG_LEVEL: "info"
  RUST_LOG: avs=debug
  AGG_IDLE_START: true
  AGG_RUN_TRIGGER_API_KEY: "secrettoken"

#####################
# gaspAvs configs #
#####################
gaspAvsEnabled: true
# Override the image tag provided on deployment from IMAGE_TAG env variable
# gaspAvsImageTag: ba3aaf237234092ad21bf0a4c5ff0f08523ba6f0

gaspAvsEnvSecrets:
  ECDSA_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/rollup-prod-operator-01-ecdsa-key
  ECDSA_KEY_PASSWORD: ref+gcpsecrets://direct-pixel-353917/rollup-prod-operator-01-ecdsa-password
  BLS_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/rollup-prod-operator-01-bls-key
  BLS_KEY_PASSWORD: ref+gcpsecrets://direct-pixel-353917/rollup-prod-operator-01-bls-password
  ETH_RPC_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetHttpsUrl
  ETH_WS_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
gaspAvsData:
  storageClass: node-data-volume-retain
  storageSize: 150Gi
gaspAvsEnv:
  CHAIN_ID: "1"
  AVS_BLOCK_VALIDATION_PERIOD: "100"
  AVS_DEBOUNCE_RPC: "20"
  AVS_DEPLOYMENT_BLOCK: "21394442"
  AVS_KICK_PERIOD: "25"
  AVS_REGISTRY_COORDINATOR_ADDR: "0x9A986296d45C327dAa5998519AE1B3757F1e6Ba1"
  AVS_RPC_URL: http://avs-aggregator:8090
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_TASK_EXPIRATION: "300"
  AVS_UPDATE_STAKE_PERIOD: "150"
  OPT_IN_AT_STARTUP: "true"
  LOG_LEVEL: "info"
  RUST_LOG: avs=debug,ether=info
  # rollup-node configs
  ROLLUP_NODE_CHAIN: /app/mainnet-chainspec.json
  ROLLUP_NODE_BOOTNODE: /dns4/collator-01-p2p-rollup-prod.gasp.xyz/tcp/30333/ws/p2p/12D3KooWCnxPCDhnSDfw3WQReZxkyJ5fuQUFzVHmQx4SwVkd2Ndo

###########################
# updater configs #
###########################
updaterEnabled: false
updaterEnvSecrets:
  ECDSA_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/rollup-prod-updater-key
  ECDSA_KEY_PASSWORD: ref+gcpsecrets://direct-pixel-353917/rollup-prod-updater-password
  ROOT_ECDSA_KEY_JSON: '{"address":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"26e1ebd941909ddb0ebaec8235470c8d"},"ciphertext":"adca2a84713f50c3918235e109a9b4b28ff6c8ea77b87e8aca20dc48a3a93389","kdf":"scrypt","kdfparams":{"dklen":32,"n":8192,"p":1,"r":8,"salt":"b5581b95b5c7f1449cc341db8567d4c92e4fe21bc34052dbe60bd3e2060a74a0"},"mac":"3643a9e1c0381e30ca0e250999810ecb4b213bc93bd19ad673b93870c77f55ec"},"id":"d39afde8-e06c-46d4-a7ed-1af9bb3f55a5","version":3}'
  SOURCE_RPC_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetHttpsUrl
  SOURCE_WS_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  TARGET_RPC_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetHttpsUrl
  TARGET_WS_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetWssUrl
updaterEnv:
  SOURCE_CHAIN_ID: 1
  TARGET_CHAIN_ID: 42161
  TARGET_CHAIN_INDEX: 1
  AVS_REGISTRY_COORDINATOR_ADDR: 0x9A986296d45C327dAa5998519AE1B3757F1e6Ba1
  GASP_SERVICE_ADDR: 0x150FE8DBB943c372F3e8C31d9c89f1E6A13cBBFd
  TESTNET: "false"
  PUSH_FIRST_INIT: "false"

updaterEnvSecretsBase:
  ECDSA_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/rollup-prod-updater-key
  ECDSA_KEY_PASSWORD: ref+gcpsecrets://direct-pixel-353917/rollup-prod-updater-password
  ROOT_ECDSA_KEY_JSON: '{"address":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"26e1ebd941909ddb0ebaec8235470c8d"},"ciphertext":"adca2a84713f50c3918235e109a9b4b28ff6c8ea77b87e8aca20dc48a3a93389","kdf":"scrypt","kdfparams":{"dklen":32,"n":8192,"p":1,"r":8,"salt":"b5581b95b5c7f1449cc341db8567d4c92e4fe21bc34052dbe60bd3e2060a74a0"},"mac":"3643a9e1c0381e30ca0e250999810ecb4b213bc93bd19ad673b93870c77f55ec"},"id":"d39afde8-e06c-46d4-a7ed-1af9bb3f55a5","version":3}'
  SOURCE_RPC_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetHttpsUrl
  SOURCE_WS_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  TARGET_RPC_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
  TARGET_WS_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
updaterEnvBase:
  SOURCE_CHAIN_ID: 1
  TARGET_CHAIN_ID: 8453
  TARGET_CHAIN_INDEX: 2
  AVS_REGISTRY_COORDINATOR_ADDR: 0x9A986296d45C327dAa5998519AE1B3757F1e6Ba1
  GASP_SERVICE_ADDR: 0x308e483afDD225D6cb7bF4d44B8e4a03DFD9c0De
  TESTNET: "false"
  PUSH_FIRST_INIT: "false"

############################
# sequencer configs #
############################
sequencerEnabled: true
# Override the image tag provided on deployment from IMAGE_TAG env variable
# sequencerImageTag: b4eac04bc26af897711c74a4309d5c659178d75f

sequencerEnvEth:
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x79d968d9017B96f202aD4673A2c1BBbdc905A4ca"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsEth:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-eth-1
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-eth-1
sequencerEnalbedEth2: true
sequencerEnvEth2:
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x79d968d9017B96f202aD4673A2c1BBbdc905A4ca"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsEth2:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-eth-2
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-eth-2
sequencerEnalbedEth3: true
sequencerEnvEth3:
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x79d968d9017B96f202aD4673A2c1BBbdc905A4ca"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsEth3:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-eth-3
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-eth-3

sequencerEnvArb:
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x3aDdEb54ddd43Eb40235eC32DfA7928F28A44bb5"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsArb:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-arb-1
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-arb-1
sequencerEnalbedArb2: true
sequencerEnvArb2:
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x3aDdEb54ddd43Eb40235eC32DfA7928F28A44bb5"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsArb2:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-arb-2
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-arb-2
sequencerEnalbedArb3: true
sequencerEnvArb3:
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x3aDdEb54ddd43Eb40235eC32DfA7928F28A44bb5"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsArb3:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-arb-3
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-arb-3

sequencerEnvBase:
  L1_CHAIN: "Base"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x308e483afDD225D6cb7bF4d44B8e4a03DFD9c0De"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-base-1
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-base-1
sequencerEnalbedBase2: true
sequencerEnvBase2:
  L1_CHAIN: "Base"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x308e483afDD225D6cb7bF4d44B8e4a03DFD9c0De"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsBase2:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-base-2
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-base-2
sequencerEnalbedBase3: true
sequencerEnvBase3:
  L1_CHAIN: "Base"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x308e483afDD225D6cb7bF4d44B8e4a03DFD9c0De"
  LIMIT: "5000"
  WATCHDOG: 300
sequencerEnvSecretsBase3:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-base-3
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-sequencer-base-3

#########################
# ferry-deposit configs #
#########################
ferryDepositEnabled: true
ferryDepositEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x79d968d9017B96f202aD4673A2c1BBbdc905A4ca"
  L1_CHAIN: "ethereum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 15
  LOG: silly
ferryDepositEnvSecretsEth:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-ferry-deposit-eth

ferryDepositEnvArb:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x3aDdEb54ddd43Eb40235eC32DfA7928F28A44bb5"
  L1_CHAIN: "arbitrum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 15
  LOG: silly
ferryDepositEnvSecretsArb:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetWssUrl
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-ferry-deposit-arb

ferryDepositEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x308e483afDD225D6cb7bF4d44B8e4a03DFD9c0De"
  L1_CHAIN: "base"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 15
  LOG: silly
ferryDepositEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
  MNEMONIC: ref+gcpsecrets://direct-pixel-353917/rollup-prod-ferry-deposit-base

############################
# ferry-withdrawal configs #
############################
ferryWithdrawalEnabled: true
ferryWithdrawalEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x79d968d9017B96f202aD4673A2c1BBbdc905A4ca"
  L1_CHAIN: "ethereum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 6
  LOG: silly
ferryWithdrawalEnvSecretsEth:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-ferry-withdrawal-private-key

ferryWithdrawalEnvArb:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x3aDdEb54ddd43Eb40235eC32DfA7928F28A44bb5"
  L1_CHAIN: "arbitrum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 6
  LOG: silly
ferryWithdrawalEnvSecretsArb:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-ferry-withdrawal-private-key

ferryWithdrawalEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x308e483afDD225D6cb7bF4d44B8e4a03DFD9c0De"
  L1_CHAIN: "base"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 6
  LOG: silly
ferryWithdrawalEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-ferry-withdrawal-private-key

########################
# ferry-closer configs #
########################
closerEnabled: true
closerEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x79d968d9017B96f202aD4673A2c1BBbdc905A4ca"
  L1_CHAIN: "ethereum"
  TOKENS_TO_TRACK: '[["0x0000000000000000000000000000000000000000", 1, 1]]'
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
closerEnvSecretsEth:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/ethereumMainnetWssUrl
  # Address: 0x343B8ef618234D46D6cD1d6f3762BA4f8d42F40C
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-closer-private-key

closerEnvArb:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x3aDdEb54ddd43Eb40235eC32DfA7928F28A44bb5"
  L1_CHAIN: "arbitrum"
  TOKENS_TO_TRACK: '[["0x0000000000000000000000000000000000000000", 1, 1]]'
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
closerEnvSecretsArb:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/arbitrumMainnetWssUrl
  # Address: 0x343B8ef618234D46D6cD1d6f3762BA4f8d42F40C
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-closer-private-key

closerEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x308e483afDD225D6cb7bF4d44B8e4a03DFD9c0De"
  L1_CHAIN: "base"
  TOKENS_TO_TRACK: '[["0x0000000000000000000000000000000000000000", 1, 1]]'
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
closerEnvSecretsBase:
  ETH_CHAIN_URL: ref+sops://secrets.enc.yaml#/baseMainnetWssUrl
  # Address: 0x343B8ef618234D46D6cD1d6f3762BA4f8d42F40C
  PRIVATE_KEY: ref+gcpsecrets://direct-pixel-353917/rollup-prod-closer-private-key
