remoteCluster: true
blockscoutEnabled: true
enableArbitrumServices: true
enableBaseServices: true
##################################
# contracts && evm-node configs #
##################################
contractsImageTag: 612242d8acb1ebe086c1508d2d015653f7d1fffc
evmNode:
  enabled: true
  customGenesisUrlEth: https://raw.githubusercontent.com/gasp-xyz/chainspec/refs/heads/master/reth/31337.json
  customGenesisUrlArb: https://raw.githubusercontent.com/gasp-xyz/chainspec/refs/heads/master/reth/31338.json
  customGenesisUrlBase: https://raw.githubusercontent.com/gasp-xyz/chainspec/refs/heads/master/reth/31339.json
#####################
# collator configs #
#####################
collatorsEnabled: true
collatorRpcNodesEnabled: false
collator:
  resources:
    requests:
      cpu: 6
      memory: 12Gi
    limits:
      cpu: 6
      memory: 12Gi
  image:
    repository: gaspxyz/rollup-node
    tag: e748b143c089828bf7dfe562e55d3f1aaa6f8478-fast
  disableChainspecGeneration: true
  customChainspecUrl: https://raw.githubusercontent.com/gasp-xyz/chainspec/7358269f21bf921b541f07db5ab80badb03288b7/rollup-dev-env-chainspecs/rollup-frontend-456a53b-raw.json
  storageClass: node-data-volume-retain
  storageSize: 50Gi
  enableServiceMonitorCollectors: true
  wsHealthExporter:
    enabled: true
    image: paritytech/ws-health-exporter:bc071a44-20230830
    env:
      WSHE_NODE_MIN_PEERS: 2
  tolerations:
    - key: production
      operator: Equal
      value: "true"
      effect: NoSchedule
  collator01:
    # Identity ID: 12D3KooWEPyq7mzPhc4DPdcm8pHvxLeQ1iuDNzhHkRUFRXBKaUa8
    customNodeKey: "dce6faa9458a24a239637edb333331aacd1f0bc4826602176cf1e57d5110da94"
    bootnodeAddr: /dns/collator-02-p2p/tcp/30333/p2p/12D3KooWS6TFRx9X4HbgLjxdD6utb6EevFH7AUNWWAKpeBquzhNQ
    extraArgs:
      - --alith
      - --pruning=archive
    nodeSelector:
      production: "true"
  collator02:
    # Identity ID: 12D3KooWS6TFRx9X4HbgLjxdD6utb6EevFH7AUNWWAKpeBquzhNQ
    customNodeKey: "f96746969e2962e3eb0327efeef0124d8db3c7993b5f3caaa08e1144263154ec"
    bootnodeAddr: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWEPyq7mzPhc4DPdcm8pHvxLeQ1iuDNzhHkRUFRXBKaUa8
    extraArgs:
      - --baltathar
      - --pruning=archive
    nodeSelector:
      production: "true"
######################
# aggregator configs #
######################
aggregatorEnabled: true
aggregatorImageTag: a98a7610b7502704f5cc57fcbc2e611a94abf757
# tests/keys/aggregator.ecdsa.key.json
aggregatorEnvSecrets:
  ECDSA_KEY_JSON: '{"address":"a0ee7a142d267c1f36714e4a8f75612f20a79720","crypto":{"cipher":"aes-128-ctr","ciphertext":"b0f6f8e3ba33f0b382b080de6661d827181de480f1a4f94bc20d66cb3d585907","cipherparams":{"iv":"4e3f9a8ca6ef8d1cd408e8aaae3c22d2"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c8f9f8cc03913e09cee7e1fd68732fac327576203ab277d740270f1dea82ee7e"},"mac":"353d65850b20d5fdb90ca2385c52e5b57662cb1d906fd58143f20a7720723cf6"},"id":"d3036cc7-d068-4f2f-9667-60aaca660e61","version":3}'
aggregatorEnv:
  # rpc
  ETH_RPC_URL: http://evm-node-eth:8545
  ETH_WS_URL: ws://evm-node-eth:8546
  SUBSTRATE_RPC_URL: ws://collator-01:9944
  # contracts
  CHAIN_ID: "1337"
  AVS_REGISTRY_COORDINATOR_ADDR: 0xf5059a5D33d5853360D16C683c16e67980206f36
  # AVS
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_BLOCK_VALIDATION_PERIOD: "5"
  # OP
  TESTNET: "true"
  ECDSA_EPHEMERAL_KEY: "true"
  BLS_EPHEMERAL_KEY: "true"
  AVS_KICK_PERIOD: 5
  AVS_MIN_OP_UPDATE_INTERVAL: 1
  AGG_IDLE_START: false
  AGG_RUN_TRIGGER_API_KEY: ""
  AVS_ENABLE_KICKER: true
  AGG_OSU_REINIT_OP: false
  AGG_OSU_CHECK_UPDATE_TRIGGER: true
  AGG_OSU_CHECK_UPDATE_TRIGGER_WINDOW: true
#####################
# gaspAvs configs #
#####################
gaspAvsEnabled: true
gaspAvsImageTag: e748b143c089828bf7dfe562e55d3f1aaa6f8478-fast
gaspAvsData:
  storageClass: node-data-volume-retain
  mountPath: /data
  storageSize: 100Gi
gaspAvsEnvSecrets:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/preregisteredGaspAvsEcdsaKeyJson
  BLS_KEY_JSON: ref+sops://secrets.enc.yaml#/preregisteredGaspAvsBlsKeyJson
gaspAvsEnv:
  CHAIN_ID: "1337"
  RUST_LOG: info,substrate=warn
  ETH_RPC_URL: http://evm-node-eth:8545
  ETH_WS_URL: ws://evm-node-eth:8546
  SUBSTRATE_RPC_URL: ws://collator-01:9944
  AVS_REGISTRY_COORDINATOR_ADDR: 0xf5059a5D33d5853360D16C683c16e67980206f36
  AVS_RPC_URL: http://avs-aggregator:8090
  TESTNET: "true"
  # rollup-node configs
  ROLLUP_NODE_BOOTNODE: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWEPyq7mzPhc4DPdcm8pHvxLeQ1iuDNzhHkRUFRXBKaUa8
  ROLLUP_NODE_CUSTOM_CHAINSPEC_URL: https://raw.githubusercontent.com/gasp-xyz/chainspec/7358269f21bf921b541f07db5ab80badb03288b7/rollup-dev-env-chainspecs/rollup-frontend-456a53b-raw.json
###########################
# updater configs #
###########################
updaterEnabled: true
updaterImageTag: 612242d8acb1ebe086c1508d2d015653f7d1fffc
updaterEnvSecrets:
  ECDSA_KEY_JSON: '{"address":"a0ee7a142d267c1f36714e4a8f75612f20a79720","crypto":{"cipher":"aes-128-ctr","ciphertext":"b0f6f8e3ba33f0b382b080de6661d827181de480f1a4f94bc20d66cb3d585907","cipherparams":{"iv":"4e3f9a8ca6ef8d1cd408e8aaae3c22d2"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c8f9f8cc03913e09cee7e1fd68732fac327576203ab277d740270f1dea82ee7e"},"mac":"353d65850b20d5fdb90ca2385c52e5b57662cb1d906fd58143f20a7720723cf6"},"id":"d3036cc7-d068-4f2f-9667-60aaca660e61","version":3}'
  ROOT_ECDSA_KEY_JSON: '{"address":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"26e1ebd941909ddb0ebaec8235470c8d"},"ciphertext":"adca2a84713f50c3918235e109a9b4b28ff6c8ea77b87e8aca20dc48a3a93389","kdf":"scrypt","kdfparams":{"dklen":32,"n":8192,"p":1,"r":8,"salt":"b5581b95b5c7f1449cc341db8567d4c92e4fe21bc34052dbe60bd3e2060a74a0"},"mac":"3643a9e1c0381e30ca0e250999810ecb4b213bc93bd19ad673b93870c77f55ec"},"id":"d39afde8-e06c-46d4-a7ed-1af9bb3f55a5","version":3}'
updaterEnv:
  SOURCE_RPC_URL: http://evm-node-eth:8545
  SOURCE_WS_URL: ws://evm-node-eth:8546
  TARGET_RPC_URL: http://evm-node-arb:8545
  TARGET_WS_URL: ws://evm-node-arb:8546
  SOURCE_CHAIN_ID: 1337
  TARGET_CHAIN_ID: 1337
  TARGET_CHAIN_INDEX: 1
  AVS_REGISTRY_COORDINATOR_ADDR: 0xf5059a5D33d5853360D16C683c16e67980206f36
  GASP_SERVICE_ADDR: 0x610178dA211FEF7D417bC0e6FeD39F05609AD788
  TESTNET: "true"
  PUSH_FIRST_INIT: "true"
  RUST_LOG: "debug"
  RUST_BACKTRACE: 1
updaterEnvSecretsBase:
  ECDSA_KEY_JSON: '{"address":"a0ee7a142d267c1f36714e4a8f75612f20a79720","crypto":{"cipher":"aes-128-ctr","ciphertext":"b0f6f8e3ba33f0b382b080de6661d827181de480f1a4f94bc20d66cb3d585907","cipherparams":{"iv":"4e3f9a8ca6ef8d1cd408e8aaae3c22d2"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c8f9f8cc03913e09cee7e1fd68732fac327576203ab277d740270f1dea82ee7e"},"mac":"353d65850b20d5fdb90ca2385c52e5b57662cb1d906fd58143f20a7720723cf6"},"id":"d3036cc7-d068-4f2f-9667-60aaca660e61","version":3}'
  ROOT_ECDSA_KEY_JSON: '{"address":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"26e1ebd941909ddb0ebaec8235470c8d"},"ciphertext":"adca2a84713f50c3918235e109a9b4b28ff6c8ea77b87e8aca20dc48a3a93389","kdf":"scrypt","kdfparams":{"dklen":32,"n":8192,"p":1,"r":8,"salt":"b5581b95b5c7f1449cc341db8567d4c92e4fe21bc34052dbe60bd3e2060a74a0"},"mac":"3643a9e1c0381e30ca0e250999810ecb4b213bc93bd19ad673b93870c77f55ec"},"id":"d39afde8-e06c-46d4-a7ed-1af9bb3f55a5","version":3}'
updaterEnvBase:
  SOURCE_RPC_URL: http://evm-node-eth:8545
  SOURCE_WS_URL: ws://evm-node-eth:8546
  TARGET_RPC_URL: http://evm-node-arb:8545
  TARGET_WS_URL: ws://evm-node-arb:8546
  SOURCE_CHAIN_ID: 1337
  TARGET_CHAIN_ID: 1337
  TARGET_CHAIN_INDEX: 1
  AVS_REGISTRY_COORDINATOR_ADDR: 0xf5059a5D33d5853360D16C683c16e67980206f36
  GASP_SERVICE_ADDR: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
  TESTNET: "true"
  PUSH_FIRST_INIT: "true"
  RUST_LOG: "debug"
  RUST_BACKTRACE: 1
############################
# sequencer configs #
############################
sequencerEnabled: true
sequencerImageTag: 612242d8acb1ebe086c1508d2d015653f7d1fffc
sequencerEnvEth:
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc"
  TX_COST: "1000000000000000000000"
  ETH_CHAIN_URL: ws://evm-node-eth:8546
  LIMIT: 10000
  WATCHDOG: 300
sequencerEnvSecretsEth:
  PRIVATE_KEY: "0x8075991ce870b93a8870eca0c0f91913d12f47948ca0fd25b49c6fa7cdbeee8b"
  MNEMONIC: "0x8075991ce870b93a8870eca0c0f91913d12f47948ca0fd25b49c6fa7cdbeee8b"
sequencerEnvArb:
  CHAIN: "reth"
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  TX_COST: "1000000000000000000000"
  ETH_CHAIN_URL: ws://evm-node-arb:8546
  LIMIT: 10000
  WATCHDOG: 300
sequencerEnvSecretsArb:
  PRIVATE_KEY: "0x0b6e18cafb6ed99687ec547bd28139cafdd2bffe70e6b688025de6b445aa5c5b"
  MNEMONIC: "0x0b6e18cafb6ed99687ec547bd28139cafdd2bffe70e6b688025de6b445aa5c5b"
sequencerEnvBase:
  CHAIN: "reth"
  L1_CHAIN: "Base"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  TX_COST: "1000000000000000000000"
  ETH_CHAIN_URL: ws://evm-node-base:8546
  LIMIT: 10000
  WATCHDOG: 30
sequencerEnvSecretsBase:
  PRIVATE_KEY: "0x39539ab1876910bbf3a223d84a29e28f1cb4e2e456503e7e91ed39b2e7223d68"
  MNEMONIC: "0x39539ab1876910bbf3a223d84a29e28f1cb4e2e456503e7e91ed39b2e7223d68"
#########################
# ferry-deposit configs #
#########################
ferryDepositEnabled: false
ferryDepositImageTag: 612242d8acb1ebe086c1508d2d015653f7d1fffc
ferryDepositEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-eth:8546
  MANGATA_CONTRACT_ADDRESS: "0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc"
  L1_CHAIN: "Ethereum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 0
  LOG: silly
ferryDepositEnvSecretsEth:
  MNEMONIC: "0x0b6e18cafb6ed99687ec547bd28139cafdd2bffe70e6b688025de6b445aa5c5b"
ferryDepositEnvArb:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-arb:8546
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  L1_CHAIN: "Arbitrum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 0
  LOG: silly
ferryDepositEnvSecretsArb:
  MNEMONIC: "0x0b6e18cafb6ed99687ec547bd28139cafdd2bffe70e6b688025de6b445aa5c5b"
ferryDepositEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-base:8546
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  L1_CHAIN: "Base"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  BLOCK_DELAY: 0
  LOG: silly
ferryDepositEnvSecretsBase:
  MNEMONIC: "0x0b6e18cafb6ed99687ec547bd28139cafdd2bffe70e6b688025de6b445aa5c5b"
############################
# ferry-withdrawal configs #
############################
ferryWithdrawalEnabled: false
ferryWithdrawalImageTag: 612242d8acb1ebe086c1508d2d015653f7d1fffc
ferryWithdrawalEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-eth:8546
  MANGATA_CONTRACT_ADDRESS: "0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc"
  L1_CHAIN: "reth-ethereum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  STASH_URL: http://127.0.0.1
ferryWithdrawalEnvSecretsEth:
  PRIVATE_KEY: "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"
ferryWithdrawalEnvArb:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-arb:8546
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  L1_CHAIN: "reth-arbitrum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  STASH_URL: http://127.0.0.1
ferryWithdrawalEnvSecretsArb:
  PRIVATE_KEY: "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"
ferryWithdrawalEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-base:8546
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  L1_CHAIN: "reth-base"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  STASH_URL: http://127.0.0.1
ferryWithdrawalEnvSecretsBase:
  PRIVATE_KEY: "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"
########################
# ferry-closer configs #
########################
closerEnabled: true
closerImageTag: 0226df257ba55a112510763da171e134c15b4ecf
closerEnvEth:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-eth:8546
  MANGATA_CONTRACT_ADDRESS: "0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc"
  L1_CHAIN: "reth-ethereum"
  TOKENS_TO_TRACK: '[["0xc351628EB244ec633d5f21fBD6621e1a683B1181", 1 ,1]]'
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  BATCH_SIZE: 5
closerEnvSecretsEth:
  PRIVATE_KEY: "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"
  STASH_URL: ref+sops://secrets.enc.yaml#/stagingStashUrl
closerEnvArb:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-arb:8546
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  L1_CHAIN: "reth-arbitrum"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  BATCH_SIZE: 5
closerEnvSecretsArb:
  PRIVATE_KEY: "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"
  STASH_URL: ref+sops://secrets.enc.yaml#/stagingStashUrl
closerEnvBase:
  MANGATA_NODE_URL: ws://collator-01:9944
  ETH_CHAIN_URL: ws://evm-node-base:8546
  MANGATA_CONTRACT_ADDRESS: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  L1_CHAIN: "reth-base"
  TOKENS_TO_TRACK: "[]"
  TX_COST: "1000000000000000000000"
  LOOK_BACK_HOURS: 1
  LOG: silly
  BATCH_SIZE: 5
closerEnvSecretsBase:
  PRIVATE_KEY: "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"
  STASH_URL: ref+sops://secrets.enc.yaml#/stagingStashUrl
