name: App Engine Deploy
description: Deploy code to the GCP App Engine

runs:
  using: composite
  steps:
    - name: Google auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - id: deploy
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        deliverables: "stash-dev/app-${{ env.APP_ENV }}.yaml"
    - id: smoke-test
      shell: bash
      run: |
        curl "${{ steps.deploy.outputs.url }}"
        echo "Deployed to ${{ steps.deploy.outputs.url }}"
