services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:nightly-2f4b5dbe7f04d974bf99625325200d214089ee66
    platform: linux/amd64
    ports:
      - 8545:8545
    entrypoint: anvil
    command: --host 0.0.0.0 --disable-block-gas-limit  --balance 1000000000000000000
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "8545"]
      interval: 2s
      timeout: 10s
      retries: 3
