services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    platform: linux/amd64
    ports:
      - 8545:8545
    # changed entrypoint because the default 'bash -c' entrypoint wasn't working the intended way...
    entrypoint: anvil
    volumes:
      - ../../tests/integration/avs-and-eigenlayer-deployed-anvil-state.json:/root/.anvil/state.json
    command: --host 0.0.0.0 --load-state /root/.anvil/state.json
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "8545"]
      interval: 2s
      timeout: 10s
      retries: 3
