#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod i_incredible_squaring_task_manager;
pub mod incredible_squaring_service_manager;
pub mod incredible_squaring_task_manager;
pub mod incredible_squaring_task_manager_test;
pub mod shared_types;
