services:
  eth-stub:
    image: gaspxyz/foundry:nightly-c2e529786c07ee7069cefcd4fe2db41f0e46cef6
    platform: linux/amd64
    ports:
      - 8545:8545
    entrypoint: anvil
    command: >
      --host 0.0.0.0 --balance 1000000000000000000 --chain-id 31337 --port 8545
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]
      interval: 2s
      timeout: 10s
      retries: 3

  arbitrum-stub:
    image: gaspxyz/foundry:nightly-c2e529786c07ee7069cefcd4fe2db41f0e46cef6
    platform: linux/amd64
    ports:
      - 8546:8545
    entrypoint: anvil
    command: >
      --host 0.0.0.0 --balance 1000000000000000000 --chain-id 31338 --port 8545
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]
      interval: 2s
      timeout: 10s
      retries: 3

  base-stub:
    image: gaspxyz/foundry:nightly-c2e529786c07ee7069cefcd4fe2db41f0e46cef6
    platform: linux/amd64
    ports:
      - 8547:8545
    entrypoint: anvil
    command: >
      --host 0.0.0.0 --balance 1000000000000000000 --chain-id 31339 --port 8545
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]
      interval: 2s
      timeout: 10s
      retries: 3
