services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    command: ["anvil", "--port", "8545", "--chain-id", "31337"]
    ports:
      - "8545:8545"
    networks:
      - localnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 4s

  benchmarks:
    image: ghcr.io/foundry-rs/foundry
    container_name: benchmarks
    depends_on:
      - anvil
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - MNEMONIC="test test test test test test test test test test test junk"
    entrypoint: >
      forge script script/RolldownGasUsage.s.sol:RolldownGasUsage --rpc-url http://anvil:8545 --broadcast
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
