services:
  eth-stub:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/paradigmxyz/reth:v1.0.7
        RUN apt-get update && apt-get install -y wget netcat && rm -rf /var/lib/apt/lists/*
    ports:
      - 8545:8545
    command:
      - node
      - "--datadir=/data"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.port=8545"
      - "--http.api=all"
      - "--http.corsdomain=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.port=8545"
      - "--ws.api=all"
      - "--ws.origins=*"
      - "--auto-mine"
      # In case the problem may reappear again
      # Ref: https://mangatafinance.slack.com/archives/G01FB4YHGMT/p1727947361912019?thread_ts=1727862030.716929&cid=G01FB4YHGMT
      # - '--dev.block-time=1s'
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]
      interval: 10s
      timeout: 5s
      retries: 3

  arbitrum-stub:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/paradigmxyz/reth:v1.0.7
        RUN apt-get update && apt-get install -y wget netcat && rm -rf /var/lib/apt/lists/*
    ports:
      - 8645:8546
    command:
      - node
      - "--datadir=/data"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.port=8545"
      - "--http.api=all"
      - "--http.corsdomain=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.port=8545"
      - "--ws.api=all"
      - "--ws.origins=*"
      - "--auto-mine"
      # In case the problem may reappear again
      # Ref: https://mangatafinance.slack.com/archives/G01FB4YHGMT/p1727947361912019?thread_ts=1727862030.716929&cid=G01FB4YHGMT
      # - '--dev.block-time=1s'
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]
      interval: 10s
      timeout: 5s
      retries: 3

  base-stub:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/paradigmxyz/reth:v1.0.7
        RUN apt-get update && apt-get install -y wget netcat && rm -rf /var/lib/apt/lists/*
    ports:
      - 8745:8547
    command:
      - node
      - "--datadir=/data"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.port=8545"
      - "--http.api=all"
      - "--http.corsdomain=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.port=8545"
      - "--ws.api=all"
      - "--ws.origins=*"
      - "--auto-mine"
      # In case the problem may reappear again
      # Ref: https://mangatafinance.slack.com/archives/G01FB4YHGMT/p1727947361912019?thread_ts=1727862030.716929&cid=G01FB4YHGMT
      # - '--dev.block-time=1s'
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]
      interval: 10s
      timeout: 5s
      retries: 3
