services:
  eth-stub:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/paradigmxyz/reth:v1.0.7
        RUN apt-get update && apt-get install -y wget netcat && rm -rf /var/lib/apt/lists/*
    ports:
      - 8545:8545
      - 8546:8546
    command:
        - node
        - '--datadir=/data'
        - '--http'
        - '--http.addr=0.0.0.0'
        - '--http.port=8545'
        - '--http.api=all'
        - '--http.corsdomain=*'
        - '--ws'
        - '--ws.addr=0.0.0.0'
        - '--ws.port=8546'
        - '--ws.api=all'
        - '--ws.origins=*'
        - '--auto-mine'
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]
      interval: 10s
      timeout: 5s
      retries: 3

  arbitrum-stub:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/paradigmxyz/reth:v1.0.7
        RUN apt-get update && apt-get install -y wget netcat && rm -rf /var/lib/apt/lists/*
    ports:
      - 8645:8545
      - 8646:8546
    command:
        - node
        - '--datadir=/data'
        - '--http'
        - '--http.addr=0.0.0.0'
        - '--http.port=8545'
        - '--http.api=all'
        - '--http.corsdomain=*'
        - '--ws'
        - '--ws.addr=0.0.0.0'
        - '--ws.port=8546'
        - '--ws.api=all'
        - '--ws.origins=*'
        - '--auto-mine'
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8545"]      
      interval: 10s
      timeout: 5s
      retries: 3