[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

solc_version = "0.8.13"
optimizer = true
optimizer_runs = 200
via_ir = false

gas_reports = ["FinalizerTaskManager", "GaspMultiRollupService", "GaspToken", "Rolldown"]
