apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.url }}
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ include "app.name" . }}
              port:
                number: {{ .Values.port }}
  tls:
    - hosts:
        - {{ .Values.url }}
      secretName: "{{ include "app.name" . }}-tls"