apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
  {{- toYaml .Values.serviceSelector | nindent 4 }}
  ports:
    - name: rpc
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}