---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mangata-updater.name" . }}-secret"
data:
  WALLET_PRIVATE_KEY: {{ .Values.walletPrivateKey | b64enc }}
  ETH_CHAIN_URL: {{ .Values.ethChainUrl | b64enc }}