name: App Engine Remove old versions
description: Removes old versions on App Engine

runs:
  using: composite
  steps:
    - id: delete
      uses: Reviewable/appengine-remove-action@v2.1.2
      with:
        limit: 14
        credentials: ${{ env.GCP_SA_KEY }}
        service_name: "${{ env.SERVICE_NAME }}-${{ env.APP_ENV }}"
    - id: test
      shell: bash
      run: |
        echo "Versions deleted: ${{ steps.delete.outputs.versions_deleted }}"
        echo "Total deleted: ${{ steps.delete.total_deleted }}"
