# Default values rollup-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: local
command: []
args: []
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    partition: 0
nodeNameOverride: ''

## Additional args to use
env:
  LOG_LEVEL: "info"

envSecrets: {}
  # ECDSA_KEY_JSON: ''
  # ECDSA_KEY_PASSWORD: ''

nameOverride: ''

image:
  repository: mangatasolutions/avs-finalizer
  pullPolicy: Always
  ## Overrides the image tag whose default is the chart appVersion.
  tag: latest

data:
  storageClass: standard-rwo
  mountPath: /data
  storageSize: 10Gi
  # -- (string) If set, create a clone of the volume (using volumeClaimTemplates.dataSource.VolumeSnapshot) and use it to store chain data
  # kubernetesVolumeSnapshot:
  # -- (string) If set, create a clone of the volume (using volumeClaimTemplates.dataSource.PersistentVolumeClaim) and use it to store chain data
  # kubernetesVolumeToClone:

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

resources: {}
  # requests:
  #   cpu: 200m
  #   memory: 1Gi
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi

# -- Define which Nodes the Pods are scheduled on
nodeSelector: {}
# -- Grace termination period of the Pod
terminationGracePeriodSeconds: 60
# -- Tolerations for use with node taints
tolerations: []
# -- Assign custom affinity rules
affinity: {}

podAnnotations: {}
  # 'fluentbit.io/parser': 'substrate'

# -- Additional containers to run in the pod
extraContainers: []

# -- Additional init containers to run in the pod
extraInitContainers: []