releases:
  - name: evm-node-eth
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ .Values.evmNode.enabled }}
    chart: ../../../helm-charts/evm-node
    values:
      - image:
          repository: gaspxyz/gasp-contracts
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        environment: {{ .Values.environmentName }}
        nameOverride: 'evm-node-eth'
        envSelector: ethereum-stub
        enablePersistence: true
        verifierEnabled: {{ .Values | get "blockscoutEnabled" false }}
        verifierUrl: 'http://blockscout-eth-blockscout-stack-blockscout-svc:80/api'
        # If customChainspecUrlEth is not set, the node will use the default chainspec instead
        customGenesisUrl: {{ .Values | get "evmNode.customGenesisUrlEth" "" }}
  
  - name: evm-node-arb
    namespace: 'rollup-{{ .Values.environmentName }}'
    installed: {{ and .Values.evmNode.enabled .Values.enableArbitrumServices | toYaml }}
    chart: ../../../helm-charts/evm-node
    values:
      - image:
          repository: gaspxyz/gasp-contracts
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        environment: {{ .Values.environmentName }}
        nameOverride: 'evm-node-arb'
        envSelector: arbitrum-stub
        enablePersistence: true
        verifierEnabled: {{ .Values | get "blockscoutEnabled" false }}
        verifierUrl: 'http://blockscout-arb-blockscout-stack-blockscout-svc:80/api'
        # If customChainspecUrlArb is not set, the node will use the default chainspec instead
        customGenesisUrl: {{ .Values | get "evmNode.customGenesisUrlArb" "" }}