apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.name" . }}-rpc
  {{- if .Values.remoteCluster }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "node.name" . }}-rpc-{{ .Values.environment }}.{{ .Values.domainZone }}
  {{- end }}
  labels: {{- include "node.labels" . | nindent 4 }}
    service: {{ include "node.name" . }}
    isRpc: 'true'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.rpcPort }}
      name: rpc
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
    service: {{ include "node.name" . }}