helmDefaults:
  wait: true

releases:
  - name: anvil
    namespace: eigen
    chart: ./helm-charts/anvil-testnet
  - name: eigen-aggregator
    installed: true
    namespace: eigen
    chart: ./helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/aggregator
          tag: latest
        command: /aggregator
        extraArgs:
          - --config 
          - /config/aggregator.yaml
          - --credible-squaring-deployment 
          - /config/credible_squaring_avs_deployment_output.json
          - --shared-avs-contracts-deployment 
          - /config/shared_avs_contracts_deployment_output.json
          - --ecdsa-private-key 
          - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
  - name: eigen-operator
    installed: true
    namespace: eigen
    chart: ./helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/operator
          tag: latest
        rpcPort: 9010
        prometheus:
          enabled: true
        command: /operator
        extraArgs:
          - --config 
          - /config/operator.yaml
        configFiles:
          - name: operator.yaml
            content: |
              # this sets the logger level (true = info, false = debug)
              production: false
              
              operator_address: 0x860B6912C2d0337ef05bbC89b0C2CB6CbAEAB4A5
              
              # EigenLayer Slasher contract address
              # This is the address of the slasher which is deployed in the anvil saved state
              # The saved eigenlayer state is located in tests/integration/eigenlayer-deployed-anvil-state.json
              el_slasher_address: 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707
              avs_service_manager_address: 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690
              bls_operator_state_retriever_address: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
              bls_public_key_compendium_address: 0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44
              
              # ETH RPC URL
              eth_rpc_url: http://anvil:8545
              eth_ws_url: ws://anvil:8545
              ecdsa_private_key_store_path: /config/test.ecdsa.key.json
              bls_private_key_store_path: /config/test.bls.key.json
              
              # address which the aggregator listens on for operator signed messages
              aggregator_server_ip_port_address: eigen-aggregator:8090
              
              # avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
              eigen_metrics_ip_port_address: 0.0.0.0:9090
              enable_metrics: true
              node_api_ip_port_address: 0.0.0.0:9010
              enable_node_api: true
              
              # we need to register the operator on startup when running the docker compose file
              # because unfortunately we cannot register the operator previously and save it in the anvil json file
              # This is because anvil only dumps the state, and not the receipt tree, so when we restart anvil with
              # the registered operator, it's blspubkey registering event with the compendium is not present anymore,
              # and so the aggregator can't find it.... very annoying
              register_operator_on_startup: true
              
              substrate_rpc_url: wss://kusama-archive.mangata.online
          - name: test.ecdsa.key.json
            content: |
              {"address":"860b6912c2d0337ef05bbc89b0c2cb6cbaeab4a5","crypto":{"cipher":"aes-128-ctr","ciphertext":"37ab29382354906d7b33b0ad1b00c539dfb69ea85997e470baba7601b0faa373","cipherparams":{"iv":"b7642683ba782688cc4da76dd5c61fce"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"fdc108d3e6388174f4cf6d5abe6de2364c96dcc03c4f1bddb1b47b01dce742e2"},"mac":"d4fff8d963a7815a7203f8c73b3047a2e5efcefb8163e6df316cc55f79df0cc2"},"id":"0c401f60-9d1f-4918-a823-1866984f8fcd","version":3}
          - name: test.bls.key.json
            content: |
              {"pubKey":"E([643552363890320897587044283125191574906281609959531590546948318138132520777,7028377728703212953187883551402495866059211864756496641401904395458852281995])","crypto":{"cipher":"aes-128-ctr","ciphertext":"8221f69293d98ca9d46c52a2747b61755c6bb71f41e951154af3bcbc0daef2b8","cipherparams":{"iv":"d8a38c68f3400aeb93084672b6e3ae61"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c41150482e6acfc2f0fcfd68b67f28ef22de8aa3f982048bdaf793c2e3ac3730"},"mac":"879c2831169d9ac70c662ebca90b9f3cd63761d0924bdbbde0a82a306baf44cd"}}