helmDefaults:
  wait: true

releases:
  - name: anvil
    namespace: eigen
    chart: ./helm-charts/anvil-testnet
  - name: eigen-aggregator
    installed: true
    namespace: eigen
    chart: ./helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/aggregator
          tag: latest
        command: /aggregator
        extraArgs:
          - --config 
          - /config/aggregator.yaml
          - --credible-squaring-deployment 
          - /config/credible_squaring_avs_deployment_output.json
          - --shared-avs-contracts-deployment 
          - /config/shared_avs_contracts_deployment_output.json
          - --ecdsa-private-key 
          - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"