extends: semantic-release-monorepo
branches: 
  - main
  - '(stash-)+([0-9])?(.{+([0-9]),x}).x'
  - name: release
    prerelease: rc
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'