services:
  eth-ferry-deposit:
    restart: unless-stopped
    platform: linux/amd64
    image: mangatasolutions/rollup-sequencer:${ROLLUP_SEQUENCER_VERSION:-local}-eth
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    build: .
    environment:
      MANGATA_NODE_URL: ${ETH_FERRY_DEPOSIT_MANGATA_NODE_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ETH_FERRY_DEPOSIT_CHAIN_URL:-wss://ethereum.publicnode.com}
      MANGATA_CONTRACT_ADDRESS: ${MANGATA_CONTRACT_ADDRESS:-0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc}
      MNEMONIC: ${ETH_FERRY_DEPOSIT_MNEMONIC:-'//Bob'}
      L1_CHAIN: ${ETH_FERRY_DEPOSIT_L1_CHAIN:-Ethereum}

  # sequencer-arb:
  #   restart: unless-stopped
  #   platform: linux/amd64
  #   image: mangatasolutions/rollup-sequencer:${ROLLUP_SEQUENCER_VERSION:-local}-arb
  #   depends_on:
  #     arbitrum-contracts-deployment:
  #       condition: service_completed_successfully
  #     node-alice:
  #       condition: service_started
  #   build: .
  #   environment:
  #     WATCHDOG: 3600
  #     MANGATA_NODE_URL: ${ROLLUP_SEQUENCER_MANGATA_NODE_URL:-wss://collator-01-ws-rococo.mangata.online}
  #     ETH_CHAIN_URL: ${ROLLUP_SEQUENCER_ETH_CHAIN_URL_ARB:-wss://ethereum.publicnode.com}
  #     MANGATA_CONTRACT_ADDRESS: ${MANGATA_CONTRACT_ADDRESS:-0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9}
  #     MNEMONIC: ${ROLLUP_SEQUENCER_MNEMONIC_ARB:-'//Bob'}
  #     BLOCK_NUMBER_DELAY: ${ROLLUP_SEQUENCER_BLOCK_NUMBER_DELAY}
  #     L1_CHAIN: ${ROLLUP_SEQUENCER_L1_CHAIN_ARB:-Arbitrum}
