name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, closed]

permissions:
  contents: write
  id-token: write
  deployments: write
  checks: write

jobs:
  init:
    name: Set global version
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    outputs:
      GLOBAL_VERSION: ${{ steps.set_vars.outputs.GLOBAL_VERSION }}
    steps:
      - name: Set global version
        id: set_vars
        run: echo "GLOBAL_VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT
  
  build-aggregator:
    name: Build aggregator Docker image
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker login -u ${{ secrets.ORG_DOCKERHUB_USERNAME }} -p ${{ secrets.ORG_DOCKERHUB_TOKEN }}
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t mangatasolutions/aggregator:latest -f aggregator/Dockerfile .
  build-operator:
    name: Build operator Docker image
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker login -u ${{ secrets.ORG_DOCKERHUB_USERNAME }} -p ${{ secrets.ORG_DOCKERHUB_TOKEN }}
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t mangatasolutions/operator:latest -f operator/Dockerfile .
  
  deploy-fungible:
    name: Deploy fungible environment
    needs: [init, build-aggregator, build-operator]
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
    with:
      env: fungible
      version: ${{ needs.init.outputs.GLOBAL_VERSION }}

  clean-up-fungible:
    name: Delete fungible environment
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.8.2
        with:
          cluster_name: mangata-dev-alpha
          location: europe-west1

      - name: Delete Kubernetes namespace with resources for fungible environment
        run: kubectl delete namespace pr-${{ github.event.number }}
      
      - name: Delete GitHub Deployment environment
        if: always()
        uses: bobheadxi/deployments@v1.4.0
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: pr-${{ github.event.number }}

