name: Pull Request
on:
  pull_request:
    types: [labeled, opened, synchronize, unlabeled, closed]

permissions:
  contents: write
  id-token: write
  deployments: write
  checks: write
  security-events: write
  issues: write
  pull-requests: write

# The following concurrency group cancels in-progress jobs or runs on pull_request events only
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  init:
    name: Set global version and check PR title format
    # Ignore pull requests from develop, release/next, or main branches
    if: github.event.action != 'unlabeled' && github.event.action != 'closed' && !contains(fromJSON('["develop", "release/next", "main"]'), github.event.pull_request.head.ref)
    runs-on: ubuntu-24.04
    outputs:
      GLOBAL_VERSION: ${{ steps.set_vars.outputs.GLOBAL_VERSION }}
      GIT_BRANCH: ${{ steps.set_vars.outputs.GIT_BRANCH }}
      GIT_BRANCH_UNFORMATTED: ${{ steps.branch-name.outputs.current_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Test PR title for conventional commit format
        uses: actions/github-script@v7
        with:
          script: |
            const pullRequestTitle = context.payload.pull_request.title;
            console.log(`Pull request title: ${pullRequestTitle}`);
            
            // Conventional commit patterns
            const typePattern = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)/;
            const fullPattern = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9-]+\))?: .+/;
            
            if (fullPattern.test(pullRequestTitle)) {
              console.log("✅ Title matches conventional commit format");
              return;
            }
            
            // Determine specific error for helpful feedback
            let errorMessage = "";
            if (!typePattern.test(pullRequestTitle)) {
              errorMessage = "must start with a valid type (feat, fix, docs, etc.)";
            } else if (!pullRequestTitle.includes(":")) {
              errorMessage = "missing colon after type/scope";
            } else {
              errorMessage = "should follow format: type(optional-scope): description";
            }
            
            const message = [
              "### ❌ Invalid PR Title Format",
              "",
              `**Current title:** \`${pullRequestTitle}\``,
              `**Issue:** ${errorMessage}`,
              "",
              "Please edit your PR title to follow the [Conventional Commits](https://www.conventionalcommits.org/) format:",
              "```",
              "<type>(<optional-scope>): <description>",
              "```",
              "",
              "**Examples:**",
              "- `feat: add user authentication`",
              "- `fix(api): correct status code`",
              "- `docs(readme): update installation steps`",
              "",
              "### After fixing the title:",
              "1. Edit the PR title by clicking the pencil icon next to the title at the top of this page",
              "2. Make a small change to your branch and push it, or use the 'Re-run all jobs' button in the Actions tab",
              "3. Alternatively, you can push an empty commit to trigger CI: `git commit --allow-empty -m 'chore: trigger ci'`",
              "4. This will trigger the workflow to run again with your corrected PR title"
            ].join('\n');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
            
            core.setFailed("PR title doesn't match conventional commit format");

      - run: corepack enable && corepack prepare yarn@4.7.0 --activate
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - run: yarn install --immutable

      - name: Run commitlint
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
      - name: Set global version
        id: set_vars
        run: |
          echo "GLOBAL_VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "GIT_BRANCH=${{ steps.branch-name.outputs.current_branch }}" | sed "s@/@-@g" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
  
  build-and-test:
    needs: [init]
    name: '[AVS services] Build'
    uses: ./.github/workflows/reusable-build-and-test.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      version: ${{ needs.init.outputs.GLOBAL_VERSION }}
  
  gasp-node-generate-types:
    name: '[gasp-node] Generate types'
    needs: [init, build-and-test]
    uses: ./.github/workflows/reusable-gasp-node-generate-types.yml
    secrets: inherit
    with:
      branch: ${{ needs.init.outputs.GIT_BRANCH_UNFORMATTED }}
      globalVersion: ${{ needs.init.outputs.GLOBAL_VERSION }}
  
  run-e2e-test:
    name: '[e2e] Run gasp-avs and ferries e2e tests'
    needs: [init, build-and-test]
    uses: ./.github/workflows/reusable-e2e-tests.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      checks: write
    with:
      globalVersion: ${{ needs.init.outputs.GLOBAL_VERSION }}
  
  run-e2e-test-gasp-node:
    name: '[e2e] Run gasp-node and global e2e tests'
    needs: [init, build-and-test, gasp-node-generate-types]
    uses: ./.github/workflows/reusable-e2e-tests-new.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      checks: write
    with:
      globalVersion: ${{ needs.init.outputs.GLOBAL_VERSION }}

  # deploy-fungible:
  #   name: Deploy fungible environment
  #   if: |
  #     (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == ':rocket: deploy_fungible') ||
  #     (github.event_name == 'pull_request' && github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, ':rocket: deploy_fungible'))
  #   needs: [init, build-and-test, build-and-test-gasp-node, gasp-node-unit-tests-and-coverage]
  #   uses: ./.github/workflows/reusable-deploy.yml
  #   secrets: inherit
  #   with:
  #     env: fungible
  #     version: ${{ needs.init.outputs.GLOBAL_VERSION }}

  clean-up-fungible:
    name: Delete fungible environment
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'unlabeled' && github.event.label.name == ':rocket: deploy_fungible') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, ':rocket: deploy_fungible'))
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2.3.0
        with:
          cluster_name: mangata-dev-alpha
          location: europe-west1

      - name: Delete Kubernetes namespace with resources for fungible environment
        run: kubectl delete namespace rollup-pr-${{ github.event.number }}
      
      - name: Delete GitHub Deployment environment
        if: always()
        uses: bobheadxi/deployments@v1.5.0
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: pr-${{ github.event.number }}

