name: '[gasp-node] Reusable generate types workflow'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to create in gasp-dev-kit"
        type: string
        required: true
      nodeDockerImage:
        description: "Name of the gasp-node docker reference"
        type: string
        required: false
        default: "gaspxyz/rollup-node:main"
      globalVersion:
        description: "Set gasp-node version."
        type: string
        required: true
  workflow_call:
    inputs:
      branch:
        description: "Branch to create in gasp-dev-kit"
        type: string
        required: true
      nodeDockerImage:
        description: "Name of the gasp-node docker reference"
        type: string
        required: false
        default: "gaspxyz/rollup-node:main"
      globalVersion:
        description: "Set gasp-node version."
        type: string
        required: true

permissions:
  contents: write
  id-token: write
  deployments: write
  checks: write

jobs:
  generate-gasp-node-types:
    runs-on: ubuntu-latest
    env:
      NODE_DOCKER_IMAGE: ${{ inputs.nodeDockerImage || format('gaspxyz/rollup-node:{0}', inputs.globalVersion) }}
      BRANCH: ${{ inputs.branch }}
    steps:
      - uses: actions/checkout@v4

      - name: Create branch ${{ env.BRANCH }} in gasp-dev-kit
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: gasp-xyz
          repository_name: gasp-dev-kit
          new_branch_name: ${{ env.BRANCH }}
          new_branch_ref: eth-rollup-develop
          ignore_branch_exists: true
          access_token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Invoke workflow in gasp-dev-kit repo with inputs
        uses: the-actions-org/workflow-dispatch@v4
        with:
          ref: ${{ env.BRANCH }}
          workflow: pr-automation-types-rollup-solochain.yml
          repo: gasp-xyz/gasp-dev-kit
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          inputs: '{"parachainDocker": "${{ env.NODE_DOCKER_IMAGE }}", "branch": "${{ env.BRANCH }}", "nodeRepository": "gasp-xyz/gasp-monorepo", "nodeCodebaseWorkingDirectory": "mangata-repo/gasp-node"}'