name: Run AVS tests
on:
  pull_request:
    types: [opened, synchronize, closed]

  workflow_dispatch:
      inputs:
        e2eBranch:
          description: ''
          required: false
          default: 'eth-rollup-develop'

permissions:
  contents: write
  id-token: write
  deployments: write
  checks: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  init:
    name: Set global version
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    outputs:
      GLOBAL_VERSION: ${{ steps.set_vars.outputs.GLOBAL_VERSION }}
    steps:
      - name: Set global version
        id: set_vars
        run: echo "GLOBAL_VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT
  
  #build-and-test:
    #needs: [init]
    #name: Build
    #uses: ./.github/workflows/reusable-build-and-test.yml
    #secrets: inherit
    #with:
      #version: ${{ needs.init.outputs.GLOBAL_VERSION }}

  Run-AVS-tests:
    runs-on: [ubuntu-latest]
    needs: [init]
    env:
      AVS_AGGREGATOR_VERSION: 3925bdc91c10d038e8fde28dfcaa72959b335ab4
      AVS_FINALIZER_VERSION: 3925bdc91c10d038e8fde28dfcaa72959b335ab4
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      #- name: build finalizer
      #  working-directory: avs-finalizer/
      #  run: cargo +stable build --release

      - name: Start env
        run: docker compose up --wait
          
      - name: Stop unnecessary services
        run: docker stop rollup-sequencer-1 rollup-updater-1

      - name: docker ps
        run: docker ps

      - name: FINALIZER tests - install deps
        working-directory: avs-finalizer/tests/
        run: yarn install

      - name: FINALIZER tests - run tests
        working-directory: avs-finalizer/tests/
        run: yarn test

      - name: Get Agg logs
        if: success() || failure()
        run: docker logs rollup-avs-aggregator-1
      
      - name: Get Finalizer logs
        if: success() || failure()
        run: docker logs rollup-avs-finalizer-1

      - name: Get anvil logs
        if: success() || failure()
        run: docker logs rollup-anvil-1

      - name: docker ps
        run: docker ps

      - name: Stop env
        if: success() || failure() # run this step even if previous step failed
        run: docker compose down -v

      

        
  
