name: deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment for deployment"
        required: true
        type: string
      version:
        description: "Version to be assigned to the built image"
        required: true
        type: string
      cluster_name:
        description: "Name of the cluster on which to perform deployment"
        default: mangata-dev-alpha
        required: false
        type: string
  workflow_call:
    inputs:
      env:
        description: "Target environment for the deployment"
        required: true
        type: string
      version:
        description: "Version to be assigned to the built image"
        required: true
        type: string
      cluster_name:
        description: "Name of the cluster on which to perform deployment"
        default: mangata-dev-alpha
        required: false
        type: string

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV_REF: ${{ inputs.env == 'fungible' && format('pr-{0}', github.event.number) || inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: jkroepke/setup-vals@v1.1.3
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.3.0
        with:
          install-kubectl: no
          install-helm: no
          additional-helm-plugins: https://github.com/jkroepke/helm-secrets --version v4.1.1,https://github.com/aslafy-z/helm-git --version 0.14.0
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.8.2
        with:
          cluster_name: ${{ inputs.cluster_name }}
          location: europe-west1
      
      - name: Create a GitHub Deployment
        uses: bobheadxi/deployments@v1.4.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.ENV_REF }}
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

      - name: Delete the fungible env deployment before new one to allow operator to register and not fail
        if: inputs.env == 'fungible'
        run: export IMAGE_TAG=${{ inputs.version }} && export ENVIRONMENT=${{ env.ENV_REF }} && helmfile destroy -e fungible
        working-directory: ops/helmfiles
      
      - run: |
          export ENVIRONMENT=${{ env.ENV_REF }}
          export IMAGE_TAG=${{ inputs.version }}
          
          # https://dev.to/derlin/helmfile-difference-between-sync-and-apply-helm-3-28o1
          
          export HELM_DIFF_THREE_WAY_MERGE=true
          helmfile apply -e ${{ inputs.env }}
        working-directory: ops/helmfiles
      
      - name: Update the GitHub Deployment status
        uses: bobheadxi/deployments@v1.4.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: "https://rollup-finalizer-${{ env.ENV_REF }}.mangata.online"
