name: Mangata Rollup - DEV

on:
  workflow_dispatch:
  push:
    branches:
      - feat/stash-dev-migration
    paths:
      - "stash-dev/**/*"
      - ".github/**/rollup-dev**"

env:
  SERVICE_NAME: 'mangata-stash'
  APP_ENV: 'rollup-dev'
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  MANGATA_NODE_URL: 'wss://collator-01-ws-rollup-dev.mangata.online'
  REDIS_HOST: '10.15.245.67'
  REDIS_PORT: 6379
  TOKEN_FOR_PRICE_SYMBOL: 'GETH'
  TIMESERIES_HOST: 'redis-14581.c124.us-central1-1.gce.redns.redis-cloud.com'
  TIMESERIES_PORT: 14581
  TIMESERIES_PASS: ${{ secrets.TIMESERIES_PASS_ROLLUP_DEV }}
  COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to Google App Angine
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-node-dependencies
      - uses: ./.github/actions/node-service-build
      - uses: ./.github/actions/node-tests
      - uses: ./.github/actions/app-engine-env-inject
      - uses: ./.github/actions/node-service-deploy
      - uses: ./.github/actions/app-engine-delete-old-versions
