{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "node.name" . }}
  labels: {{- include "node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "node.selectorLabels" . | nindent 6 }}
      service: {{ include "node.name" . }}
  endpoints:
    - port: {{ .Values.service.name }}
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- end }}
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml . | indent 6 }}
      {{- end }}
  {{- with .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- end }}
  {{- if .Values.serviceMonitor.sampleLimit }}
  sampleLimit: {{ .Values.serviceMonitor.sampleLimit }}
  {{- end }}
  
{{- end }}
