services:
  gasp-avs:
    build:
      context: .
      args:
        ROLLUP_NODE_VERSION: ${ROLLUP_NODE_VERSION}
    image: gaspxyz/gasp-avs:${GASP_AVS_VERSION:-local}
    restart: unless-stopped
    depends_on:
      eth-stub:
        condition: service_healthy
      eth-contracts-deployment:
        condition: service_started
    volumes:
      - gasp-avs-data:/data
    environment:
      CHAIN_ID: ${CHAIN_ID:-31337}
      RUST_LOG: info
      ETH_RPC_URL: ${ETH_RPC_URL:-http://eth-stub:8545}
      ETH_WS_URL: ${ETH_WS_URL:-ws://eth-stub:8545}
      AVS_RPC_URL: ${AVS_RPC_URL:-http://avs-aggregator:8090}
      AVS_REGISTRY_COORDINATOR_ADDR: 0xf5059a5D33d5853360D16C683c16e67980206f36
      ECDSA_EPHEMERAL_KEY: true
      BLS_EPHEMERAL_KEY: true
      TESTNET: true
      # rollup-node configs
      ROLLUP_NODE_BOOTNODE: /dns/node-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      ROLLUP_NODE_CHAIN: /data/chainspec.json
      ROLLUP_NODE_CUSTOM_CHAINSPEC_URL: https://raw.githubusercontent.com/gasp-xyz/chainspec/0c05b37addc49e807a7802604e9648691bfe2a9a/rollup-dev-env-chainspecs/rollup-fungible-26de25a-raw.json
      ROLLUP_NODE_FORCE_DOWNLOAD_CHAINSPEC: false


volumes:
  gasp-avs-data: