services:
  gasp-avs:
    build:
      context: .
    image: gaspxyz/gasp-avs:${GASP_AVS_VERSION:-local}
    restart: unless-stopped
    depends_on:
      eth-stub:
        condition: service_healthy
      eth-contracts-deployment:
        condition: service_started
    environment:
      CHAIN_ID: ${CHAIN_ID:-31337}
      RUST_LOG: info
      ETH_RPC_URL: ${ETH_RPC_URL:-http://eth-stub:8545}
      ETH_WS_URL: ${ETH_WS_URL:-ws://eth-stub:8545}
      AVS_RPC_URL: ${AVS_RPC_URL:-http://avs-aggregator:8090}
      AVS_REGISTRY_COORDINATOR_ADDR: 0xf5059a5D33d5853360D16C683c16e67980206f36
      ECDSA_EPHEMERAL_KEY: true
      BLS_EPHEMERAL_KEY: true
      TESTNET: true
      OPT_IN_AT_STARTUP: true
      METRICS_PORT: 8080
      SUBSTRATE_RPC_URL: ${SUBSTRATE_RPC_URL:-ws://node-alice:9944}